import { lessonFor, metaForUnit, type ExpertiseLevel } from "./learning-catalog";
import type { PearsonTopic, PearsonUnit } from "./pearson-curriculum";

export type LearningQuestion = {
  id: string;
  kind: "single_choice" | "short_response" | "extended_response" | "practical_response";
  commandWord: "Identify" | "Describe" | "Explain" | "Analyse" | "Justify" | "Evaluate" | "Create" | "Develop" | "Test" | "Normalise" | "Debug";
  difficulty: 1 | 2 | 3 | 4;
  marks: number;
  prompt: string;
  options?: string[];
  answer?: number;
  keywords?: string[];
  minimumWords?: number;
  hint: string;
  explanation: string;
  markScheme: string[];
  modelAnswer: string;
  misconception: string;
  responseFormat?: "written" | "database_design" | "sql" | "python" | "pseudocode" | "html_css" | "javascript" | "test_table";
  starterCode?: string;
  evidenceChecklist?: string[];
};

export type PaperMode = "knowledge" | "applied" | "assignment";
export type PaperBlueprint = { mode: PaperMode; title: string; description: string; suggestedMinutes: number; questionsPerTopic: number };

const contexts = [
  "Northbridge College, which supports learners and staff across two campuses",
  "Oak & Field, a small retailer expanding its online and in-store services",
  "Riverside Community Trust, which relies on volunteers and limited funding",
  "NovaWorks, a growing technology business with remote and office-based staff",
];

export function questionsFor(unit: PearsonUnit, topic: PearsonTopic): LearningQuestion[] {
  const lesson = lessonFor(unit, topic, "Core"), concepts = topic.content;
  const concept = (index: number) => concepts[index % concepts.length];
  const distractors = unit.topics.filter(item => item.code !== topic.code).flatMap(item => item.content);
  const optionsFor = (correct: string, offset: number) => shuffleStable(unique([correct, ...distractors.slice(offset, offset + 5)]).slice(0,4), offset);
  const make = (index:number, input:Omit<LearningQuestion,"id"|"markScheme"|"modelAnswer"|"misconception"> & Partial<Pick<LearningQuestion,"markScheme"|"modelAnswer"|"misconception">>):LearningQuestion => ({
    id:`${unit.code}-${topic.code}-${index+1}`,
    markScheme: input.markScheme ?? appliedMarkScheme(concept(index), input.marks),
    modelAnswer: input.modelAnswer ?? modelResponse(contexts[index%contexts.length], concept(index), concept(index+1), input.commandWord),
    misconception: input.misconception ?? `Naming ${concept(index)} without applying it to the organisation or explaining its effect.`,
    ...input,
  });
  const mcq = (index:number, difficulty:1|2, prompt:string, correct:string, offset:number, explanation:string) => {
    const options=optionsFor(correct,offset);
    return make(index,{kind:"single_choice",commandWord:"Identify",difficulty,marks:1,prompt,options,answer:options.indexOf(correct),hint:`Eliminate options that do not belong directly to ${topic.code} ${topic.title}.`,explanation,markScheme:[`1 mark for selecting ${correct}.`],modelAnswer:correct,misconception:`Confusing ${correct} with content from a different topic.`});
  };
  return [
    mcq(0,1,`Which option is required knowledge for ${topic.code} ${topic.title}?`,concept(0),0,`${concept(0)} is explicitly required within this topic.`),
    mcq(1,2,`${contexts[0]} is addressing ${topic.title.toLowerCase()}. Which concept should it consider first?`,concept(1),3,`${concept(1)} is the most direct match. The decision must still be justified against the organisation's requirements.`),
    make(2,{kind:"short_response",commandWord:"Describe",difficulty:1,marks:2,prompt:`Describe two features or stages involved in ${concept(2)}.`,keywords:keywordRoots(`${concept(2)} ${concept(3)}`),minimumWords:30,hint:`Give two separate accurate points. Do not merely repeat the question.`,explanation:`A two-mark description needs two distinct, accurate features or stages.`,markScheme:[`1 mark for an accurate feature of ${concept(2)}.`,`1 mark for a second distinct feature or stage.`]}),
    make(3,{kind:"short_response",commandWord:"Explain",difficulty:2,marks:4,prompt:`${contexts[1]} needs to use ${concept(3)}. Explain how it would help meet one organisational requirement.`,keywords:keywordRoots(`${concept(3)} ${concept(0)}`),minimumWords:60,hint:lesson.guided.hint,explanation:`An explanation links the chosen concept to a consequence: what happens, why it happens and how it meets the stated need.`,markScheme:[`Accurate use of ${concept(3)}.`,`Application to the retailer rather than a generic definition.`,`A developed because/therefore link.`,`A relevant success check or consequence.`]}),
    mcq(4,2,`Which statement shows the strongest use of ${concept(4)}?`, `Apply it to a stated requirement and check the resulting outcome`,6,`BTEC answers gain credit for accurate knowledge that is applied to a context and supported by evidence.`),
    make(5,{kind:"short_response",commandWord:"Analyse",difficulty:3,marks:6,prompt:`Analyse how ${concept(1)} and ${concept(2)} could affect ${contexts[2]}.`,keywords:keywordRoots(`${concept(1)} ${concept(2)}`),minimumWords:100,hint:`Build a chain: factor → immediate effect → consequence for the organisation → evidence.`,explanation:`Analysis develops linked consequences and shows how the two concepts interact in this particular context.`,markScheme:[`Accurate analysis of ${concept(1)}.`,`Accurate analysis of ${concept(2)}.`,`Clear application to the community trust.`,`At least one developed chain of consequences.`,`Interaction or trade-off between the concepts.`,`Supported conclusion.`]}),
    make(6,{kind:"extended_response",commandWord:"Justify",difficulty:4,marks:8,prompt:`${contexts[3]} must make a decision about ${topic.title.toLowerCase()}. Recommend an approach and justify it using ${concept(0)}, ${concept(1)} and relevant constraints.`,keywords:keywordRoots(`${concept(0)} ${concept(1)} ${concept(2)}`),minimumWords:150,hint:`State the decision, compare a credible alternative, use the context and finish with a supported judgement.`,explanation:`A justified response makes a clear recommendation, applies accurate topic knowledge, considers an alternative and uses contextual evidence to defend the final decision.`,markScheme:[`Accurate and relevant knowledge of ${topic.title}.`,`Specific application to NovaWorks.`,`A feasible recommended approach.`,`Use of ${concept(0)} and ${concept(1)}.`,`Consideration of constraints or risks.`,`Comparison with a credible alternative.`,`Developed reasoning rather than assertions.`,`Supported final judgement.`]}),
    make(7,{kind:"extended_response",commandWord:"Evaluate",difficulty:4,marks:10,prompt:`Evaluate how effectively a proposed solution involving ${topic.title.toLowerCase()} would meet the needs of ${contexts[0]}. Include strengths, limitations, evidence and a prioritised improvement.`,keywords:keywordRoots(concepts.join(" ")),minimumWords:180,hint:`Use both sides of the argument, refer to measurable evidence, then make a reasoned overall judgement and priority.`,explanation:`Evaluation weighs strengths against limitations using evidence. The conclusion must follow from the analysis and the improvement must address the most important weakness.`,markScheme:[`Accurate breadth of topic knowledge (2).`,`Specific contextual application (2).`,`Balanced strengths and limitations (2).`,`Use of evidence or measurable success criteria (2).`,`Reasoned judgement and prioritised improvement (2).`]}),
  ];
}

export function paperBlueprintsFor(unit: PearsonUnit):PaperBlueprint[]{
  const external=unit.code==="1"||unit.code==="2"||unit.code==="14";
  return [
    {mode:"knowledge",title:"Knowledge and terminology check",description:"Short questions from every topic to secure essential vocabulary and processes.",suggestedMinutes:Math.max(20,unit.topics.length*3),questionsPerTopic:2},
    {mode:"applied",title:unit.code==="2"?"Short practical set-task practice":external?"Applied assessment practice":"Applied vocational practice",description:practicalDescription(unit,"applied"),suggestedMinutes:["2","4","6"].includes(unit.code)?90:Math.max(35,unit.topics.length*6),questionsPerTopic:2},
    {mode:"assignment",title:unit.code==="1"?"Synoptic exam rehearsal":unit.code==="2"?"Pearson-style 66-mark set-task rehearsal":unit.code==="14"?"Pearson-style IT service set-task rehearsal":"Assignment rehearsal",description:practicalDescription(unit,"assignment"),suggestedMinutes:unit.code==="2"?600:unit.code==="14"?480:["4","6"].includes(unit.code)?180:Math.max(45,unit.topics.length*8),questionsPerTopic:1},
  ];
}

export function paperQuestions(unit: PearsonUnit, version = 0, mode:PaperMode="applied") {
  if(unit.code==="2"&&mode!=="knowledge"){
    const tasks=unit2PracticalTasks(unit,version);
    return mode==="assignment"?tasks:[tasks[0],tasks[1],tasks[2+version%2],tasks[4],tasks[6]];
  }
  if(unit.code==="4"&&mode!=="knowledge")return unit4PracticalTasks(unit,version,mode);
  if(unit.code==="6"&&mode!=="knowledge")return unit6PracticalTasks(unit,version,mode);
  return unit.topics.flatMap((topic, topicIndex) => {
    const questions=questionsFor(unit,topic), variant=(version+topicIndex)%2;
    if(mode==="knowledge")return [questions[variant],questions[2+variant]];
    if(mode==="assignment")return [questions[6+variant]];
    return [questions[3+variant],questions[5+variant]];
  });
}

function practicalDescription(unit:PearsonUnit,mode:PaperMode){
  if(unit.code==="2")return mode==="assignment"
    ?"A full original database set-task: normalise UNF to 3NF, define tables and validation, create queries, forms and reports, test the solution and evaluate it."
    :"A shorter hands-on database rehearsal using normalisation, table design, SQL/query logic, forms, validation and testing.";
  if(unit.code==="4")return "A practical programming brief requiring algorithms, Python code, debugging, validation, testing and optimisation, not theory-only answers.";
  if(unit.code==="6")return "A practical website brief requiring semantic HTML, responsive CSS, JavaScript, accessibility, debugging and browser testing.";
  if(unit.code==="14")return "An original external set-task rehearsal requiring analysis of an organisation, a justified IT service solution, credible alternatives and service-management implications. It is not Pearson's live task.";
  return `A longer ${unit.code==="1"?"assessment":"vocational assignment"} rehearsal mapped to ${metaForUnit(unit.code).aims.join(", ")}.`;
}

function practicalQuestion(unit:PearsonUnit,version:number,index:number,input:Omit<LearningQuestion,"id"|"kind">):LearningQuestion{
  return{id:`${unit.code}-practical-v${version+1}-${index+1}`,kind:"practical_response",...input};
}

function unit2PracticalTasks(unit:PearsonUnit,version:number):LearningQuestion[]{
  const branch=["central service","north campus","community outreach","mobile operations","evening service","regional hub"][Math.floor(version/2)%6];
  const client=`${version%2===0?"Harbour Equipment Loans":"Greenfield Training Bookings"}: ${branch}`;
  const entity=version%2===0?"equipment item":"training course";
  const raw=version%2===0
    ?"BORROWER(BorrowerID, BorrowerName, Email, {LoanID, ItemID, ItemName, CategoryName, LoanDate, DueDate, ReturnedDate})"
    :"CUSTOMER(CustomerID, CustomerName, Email, {BookingID, CourseID, CourseTitle, TutorID, TutorName, BookingDate, Places, Fee, AmountPaid})";
  return[
    practicalQuestion(unit,version,0,{commandWord:"Normalise",difficulty:4,marks:10,responseFormat:"database_design",prompt:`Activity 1: normalisation. ${client} currently stores this repeating, unnormalised record:\n\n${raw}\n\nShow the transformation from UNF to 1NF, 2NF and 3NF. At every stage state the rule being applied, identify dependencies, and finish with named tables showing primary and foreign keys.`,keywords:keywordRoots("UNF repeating group atomic 1NF partial dependency 2NF transitive dependency 3NF primary key foreign key"),minimumWords:120,hint:"Start by removing the repeating group. Then test every non-key attribute against the whole key, and finally remove attributes that depend on another non-key attribute.",explanation:"The evidence must show the normalisation journey and the rule used at each stage; presenting only a final list of tables is incomplete.",evidenceChecklist:["UNF and repeating group identified","1NF contains atomic values","2NF removes partial dependencies","3NF removes transitive dependencies","Final PKs, FKs and relationships are clear"],markScheme:["Identifies the repeating group and suitable key(s).","Produces a valid atomic 1NF structure.","Explains the 1NF rule.","Identifies partial dependency where applicable.","Produces valid 2NF tables.","Explains the 2NF rule.","Identifies transitive dependency where applicable.","Produces valid 3NF tables.","Labels primary and foreign keys accurately.","Final relationships preserve the original data requirements."],modelAnswer:`A strong solution separates the repeating ${entity} transaction from the customer/borrower. It shows atomic 1NF rows, removes attributes dependent on only part of a composite key for 2NF, then separates descriptive attributes such as category or tutor that depend on another non-key attribute for 3NF. Every final table has a PK and each relationship is implemented by an FK.`,misconception:"Jumping directly to 3NF without showing the rules, dependencies and intermediate structures."}),
    practicalQuestion(unit,version,1,{commandWord:"Create",difficulty:3,marks:8,responseFormat:"database_design",prompt:`Activity 2: table structures and validation. Create a data-dictionary extract for the final ${client} database. Include at least eight important fields across the tables, with data type, size/format, key status, required status, validation rule and a helpful validation message.`,keywords:keywordRoots("field data type size format primary foreign required presence range lookup validation message"),minimumWords:80,hint:"Choose validation that matches the field: presence, range, format, length or lookup. Do not use a presence check where a range check is needed.",explanation:"Pearson-style evidence links each field to an appropriate storage choice and enforceable validation rule.",evidenceChecklist:["At least eight fields","Suitable types and sizes","PK/FK status","Required/presence rules","Range, format or lookup validation","User-friendly error messages"],markScheme:["Fields cover the core entities.","Data types are suitable.","Sizes or formats are justified.","Primary keys are identified.","Foreign keys are identified.","Required fields use presence validation.","Other validation rules are appropriate.","Messages tell the user how to correct invalid data."],modelAnswer:"The dictionary should include identifiers, descriptive fields, dates and numeric values. IDs use unique key rules, foreign keys use table lookup/referential integrity, names use presence and length checks, dates use sensible comparison rules, and numeric values use ranges with clear messages.",misconception:"Listing generic validation types without attaching executable rules and messages to specific fields."}),
    practicalQuestion(unit,version,2,{commandWord:"Create",difficulty:4,marks:8,responseFormat:"sql",prompt:`Activity 3a: selection query. Write SQL (or an exact query-design specification) that lists overdue ${version%2===0?"loans that have not been returned":"bookings that still have an unpaid balance"}. Join the necessary tables, show meaningful names rather than IDs, apply the correct criteria, calculate the overdue/balance value, sort the most urgent record first and use clear aliases.`,starterCode:version%2===0?"SELECT -- required fields\nFROM loan\n-- add joins and criteria\nORDER BY -- most overdue first;":"SELECT -- required fields\nFROM booking\n-- add joins, calculation and criteria\nORDER BY -- largest balance first;",keywords:keywordRoots("SELECT FROM JOIN ON WHERE IS NULL CURRENT_DATE calculated alias ORDER BY DESC"),minimumWords:35,hint:"Build it in this order: output fields → joins → calculated field → criteria → sort.",explanation:"This is assessed as a working query specification, not an essay about what queries do.",evidenceChecklist:["Correct tables joined","Useful output fields","Correct criteria","Calculated field","Clear alias","Required sort order"],markScheme:["Selects useful identifying fields.","Uses the correct transaction table.","Joins the person/customer table correctly.","Joins the item/course table correctly.","Applies the required overdue/unpaid criterion.","Creates a correct calculated value.","Uses meaningful output aliases.","Sorts in the required order."],modelAnswer:version%2===0?"SELECT b.BorrowerName, e.ItemName, l.DueDate, DateDiff('d',l.DueDate,Date()) AS DaysOverdue FROM (Borrower AS b INNER JOIN Loan AS l ON b.BorrowerID=l.BorrowerID) INNER JOIN Equipment AS e ON l.ItemID=e.ItemID WHERE l.ReturnedDate IS NULL AND l.DueDate<Date() ORDER BY DaysOverdue DESC;":"SELECT c.CustomerName, t.CourseTitle, b.BookingDate, (b.Places*b.Fee)-b.AmountPaid AS BalanceDue FROM (Customer AS c INNER JOIN Booking AS b ON c.CustomerID=b.CustomerID) INNER JOIN Course AS t ON b.CourseID=t.CourseID WHERE (b.Places*b.Fee)-b.AmountPaid>0 ORDER BY BalanceDue DESC;",misconception:"Describing the query instead of supplying SQL or a complete design-grid specification."}),
    practicalQuestion(unit,version,3,{commandWord:"Create",difficulty:4,marks:10,responseFormat:"sql",prompt:`Activity 3b: parameter and summary query. Create a query that asks for a ${version%2===0?"borrower surname":"course title"}, returns matching records, calculates a useful total and groups the results correctly. Provide the SQL or every row of the query-design grid, including the parameter, joins, calculation, grouping and sort.`,starterCode:"PARAMETERS [Enter search value:] Text;\nSELECT -- grouped fields and calculation\nFROM -- joined tables\nWHERE -- parameter criterion\nGROUP BY -- non-aggregated fields;",keywords:keywordRoots("PARAMETERS SELECT INNER JOIN WHERE GROUP BY SUM COUNT calculated alias ORDER BY"),minimumWords:45,hint:"In an aggregate query, every selected field must either be grouped or use an aggregate function such as SUM or COUNT.",explanation:"A parameter prompt, correct joins and a valid grouped calculation are all required for a usable summary query.",evidenceChecklist:["Parameter declared","Joins are valid","Aggregate calculation","GROUP BY is valid","Aliases are meaningful","Output meets the stated purpose"],markScheme:["Defines an appropriate parameter.","Uses the parameter in the criterion.","Selects relevant output fields.","Joins the first pair of tables correctly.","Joins any additional table correctly.","Uses COUNT or SUM appropriately.","Calculates the requested total correctly.","Groups every non-aggregated output field.","Uses meaningful aliases and formatting.","Produces a usable sorted result."],modelAnswer:"A valid solution declares a text parameter, applies it to the relevant name/title field, joins through the transaction table, groups the identifying fields, and calculates a count and/or sum with a clear alias. The final output is sorted for the intended user.",misconception:"Combining aggregate and non-aggregate fields without a valid GROUP BY clause."}),
    practicalQuestion(unit,version,4,{commandWord:"Develop",difficulty:4,marks:8,responseFormat:"database_design",prompt:`Activity 4: data-entry form. Specify a usable form for adding and editing ${version%2===0?"borrowers and their loans":"customers and their bookings"}. Give the record source, controls, navigation, lookup/combo boxes, calculated or locked fields, validation behaviour and one automation feature. Include a brief text wireframe or control list.`,keywords:keywordRoots("record source form subform combo box lookup validation locked calculated navigation button macro usability"),minimumWords:90,hint:"Decide what the user enters, what the database looks up, what is calculated automatically and what must be locked.",explanation:"A form is assessed through its implemented interface and functionality, not a definition of a form.",evidenceChecklist:["Record source","Logical control layout","Lookup/combo box","Locked automatic keys","Validation and messages","Navigation or action control","Automation feature"],markScheme:["Suitable record source.","Controls cover required data.","Layout supports the task.","Foreign-key choice uses a lookup/combo box.","Automatic identifiers are locked.","Validation prevents invalid saving.","Navigation/action buttons are purposeful.","Automation or calculated behaviour is specified."],modelAnswer:"Use a main customer/borrower form with a related bookings/loans subform. Display names in combo boxes while storing IDs, lock automatic keys and totals, place validation beside the relevant control, and provide clear save/new/search navigation with one automated calculation or lookup.",misconception:"Drawing attractive boxes without explaining record sources, relationships, validation and working controls."}),
    practicalQuestion(unit,version,5,{commandWord:"Create",difficulty:3,marks:6,responseFormat:"database_design",prompt:`Activity 5: management report. Design a grouped report that lets ${client} monitor activity by ${version%2===0?"equipment category":"course"}. State its record source, grouping, sort order, detail fields, calculated totals, title/header/footer information and how empty or null values are handled.`,keywords:keywordRoots("report record source group sort detail sum count calculated header footer null"),minimumWords:70,hint:"A report needs both record-level detail and group-level summaries that answer a management question.",explanation:"The report specification must be detailed enough to build and verify.",evidenceChecklist:["Record source","Grouping and sorting","Detail fields","Group totals","Overall total","Professional title/labels"],markScheme:["Record source is suitable.","Grouping supports the purpose.","Sorting is stated.","Useful detail fields are included.","A correct group calculation is specified.","Title, labels and summary information are professional."],modelAnswer:"Base the report on a query joining the transaction and lookup tables. Group by category/course, sort within each group, show key transaction details, calculate counts and totals in group footers, and show an overall total in the report footer with clear labels and null handling.",misconception:"Listing report fields without grouping, calculations or a stated decision-making purpose."}),
    practicalQuestion(unit,version,6,{commandWord:"Test",difficulty:4,marks:8,responseFormat:"test_table",prompt:`Activity 6: testing. Produce eight test rows for the database structure, query and form. Include test number, feature, test type, exact test data, expected result, actual-result evidence to capture, pass/fail and the retest action. Cover normal, boundary and erroneous data plus referential integrity and one query calculation.`,keywords:keywordRoots("test normal typical boundary extreme erroneous invalid expected actual pass fail retest referential integrity query calculation"),minimumWords:100,hint:"Use actual values. “Test invalid data” is not enough; state the invalid value and the exact message or blocked behaviour expected.",explanation:"A strong test log is repeatable and records evidence, defects, fixes and retests.",evidenceChecklist:["Eight exact tests","Normal/boundary/erroneous","Referential integrity","Validation message","Query calculation","Expected and actual evidence","Retest action"],markScheme:["Eight distinct tests are supplied.","Normal data is covered.","Boundary data is covered.","Erroneous data is covered.","Referential integrity is tested.","A query/calculation is tested.","Expected outcomes are precise.","Evidence and retest action are recorded."],modelAnswer:"Include tests for a valid record, blank required field, lower and upper boundaries, just-outside values, missing foreign key, query criteria, calculated output and form automation. Each row states exact input, expected behaviour, evidence and retest outcome.",misconception:"Using vague test descriptions or omitting actual evidence and retesting after a defect."}),
    practicalQuestion(unit,version,7,{commandWord:"Evaluate",difficulty:4,marks:8,responseFormat:"written",prompt:`Activity 7: evaluation. Evaluate the completed ${client} database against the client requirements. Use evidence from the table design, data integrity, queries, form, report and tests; identify two limitations and prioritise one justified improvement.`,keywords:keywordRoots("requirements evidence normalisation integrity query form report testing limitation improvement priority"),minimumWords:160,hint:"Organise the evaluation by requirement. Quote evidence, explain the effect on the client, then prioritise the most valuable refinement.",explanation:"Evaluation must be supported by evidence from the built solution and tests, not a list of features.",evidenceChecklist:["Requirements addressed","Evidence from implementation","Evidence from testing","Strengths and limitations","Prioritised improvement","Reasoned judgement"],markScheme:["Evaluates data structure against requirements.","Uses integrity/validation evidence.","Evaluates query usefulness.","Evaluates form usability/functionality.","Evaluates report usefulness.","Uses testing evidence.","Identifies realistic limitations.","Prioritises and justifies an improvement."],modelAnswer:"A developed evaluation traces each client requirement to implementation and test evidence, explains the operational benefit, acknowledges specific limitations, and recommends the improvement with the greatest effect on accuracy, usability or decision-making.",misconception:"Claiming the database works well without referring to requirements, test results or limitations."}),
  ];
}

function unit4PracticalTasks(unit:PearsonUnit,version:number,mode:PaperMode):LearningQuestion[]{
  const setting=["main site","satellite centre","evening team","mobile service","regional office","training branch"][Math.floor(version/2)%6];
  const context=`${version%2===0?"volunteer rota":"equipment booking"} for the ${setting}`;
  const tasks=[
    practicalQuestion(unit,version,0,{commandWord:"Create",difficulty:3,marks:6,responseFormat:"pseudocode",prompt:`Design pseudocode for a ${context} feature that accepts validated input, processes a collection of records and reports records that need action. Show decomposition, selection, iteration and at least one reusable function.`,keywords:keywordRoots("INPUT validation function parameter return FOR WHILE IF ELSE list output"),minimumWords:45,hint:"Write the function first, then the input/validation loop, then iterate through the records.",explanation:"The response must be an implementable algorithm, not a description of programming constructs.",evidenceChecklist:["Inputs and outputs","Validation loop","Selection","Iteration","Function with parameter/return","Clear variable names"],markScheme:["Defines inputs and output.","Uses a validation loop.","Uses selection correctly.","Iterates through the collection.","Decomposes logic into a function.","Algorithm is logically complete."],modelAnswer:"FUNCTION needs_action(record) RETURNS BOOLEAN ... REPEAT input UNTIL valid ... FOR EACH record IN records IF needs_action(record) THEN OUTPUT record ENDIF NEXT",misconception:"Explaining what selection and iteration mean without producing an algorithm."}),
    practicalQuestion(unit,version,1,{commandWord:"Debug",difficulty:3,marks:6,responseFormat:"python",prompt:`The following ${context} code contains logical, type and boundary errors. Produce corrected Python and annotate each fix.`,starterCode:"required = input('Required places: ')\nallocated = int(input('Allocated places: '))\nif allocated > required:\n    gap = required - allocated\nprint('Places still needed: ' + gap)",keywords:keywordRoots("int try except ValueError required allocated gap max f string validation"),minimumWords:25,hint:"Check types first, then the comparison, then the calculation and output conversion.",explanation:"Marks reward executable corrections and reasons tied to the observed faults.",evidenceChecklist:["Input converted safely","Invalid/negative input handled","Condition corrected","Gap cannot be negative","Output type corrected","Fixes explained"],markScheme:["Converts required to an integer.","Handles invalid input.","Rejects impossible negative values.","Corrects the condition or removes it safely.","Calculates a non-negative gap.","Formats output without a type error."],modelAnswer:"Use a function with try/except, reject values below zero, then `gap = max(0, required - allocated)` and output it with an f-string.",misconception:"Fixing only the final print statement while leaving the logical and validation defects."}),
    practicalQuestion(unit,version,2,{commandWord:"Develop",difficulty:4,marks:10,responseFormat:"python",prompt:`Write a complete Python function for the ${context} system. It must validate its parameters, process a list of dictionaries, calculate a useful summary, return structured results and handle an empty list. Include a short call that demonstrates the function.`,starterCode:"def analyse_records(records: list[dict]) -> dict:\n    # validate, process and return a summary\n    pass",keywords:keywordRoots("def records list dict if raise ValueError for sum return count total average"),minimumWords:45,hint:"Define the return structure before writing the loop. Make the empty-list behaviour explicit.",explanation:"This task requires working code with a clear contract, defensive validation and testable returned values.",evidenceChecklist:["Function signature","Parameter validation","List iteration","Selection/calculation","Empty-list handling","Structured return","Demonstration call"],markScheme:["Defines a suitable function.","Validates the parameter type/content.","Handles an empty list.","Iterates correctly.","Uses selection for relevant records.","Calculates a count.","Calculates a useful total/summary.","Returns structured data.","Uses readable names/comments.","Includes a valid demonstration call."],modelAnswer:"A strong solution validates that records is a list, handles empty input deliberately, loops through dictionaries using safe key access, accumulates totals and counts, and returns a dictionary that can be tested independently.",misconception:"Printing results inside one long script instead of returning testable structured output."}),
    practicalQuestion(unit,version,3,{commandWord:"Test",difficulty:4,marks:8,responseFormat:"test_table",prompt:`Create a test plan for the function you wrote. Include at least six exact tests covering typical, boundary, erroneous and empty input. For two tests, state the expected returned dictionary exactly. Then show one automated Python assertion.`,keywords:keywordRoots("typical boundary erroneous empty expected actual assert pytest exception retest"),minimumWords:85,hint:"Derive tests from every branch and validation rule in the function.",explanation:"Testing should prove behaviour at boundaries and failures, not merely run the happy path.",evidenceChecklist:["Six exact tests","Typical input","Boundary input","Erroneous input","Empty input","Exact expected values","Automated assertion"],markScheme:["At least six distinct tests.","Typical case is valid.","Boundary is identified.","Erroneous input expects safe failure.","Empty input is covered.","Expected values are precise.","An assertion is syntactically credible.","Retesting is described."],modelAnswer:"Include inputs, expected return/exception and actual evidence. An automated example is `assert analyse_records([]) == {'count': 0, 'total': 0}` if that matches the documented contract.",misconception:"Calling every valid test “normal” and omitting exact expected results."}),
    practicalQuestion(unit,version,4,{commandWord:"Evaluate",difficulty:4,marks:8,responseFormat:"python",prompt:`Refactor this design for maintainability and reliability: a 70-line main block repeats validation, uses global variables and mixes input, processing and output. Provide a revised function/module structure with one code example, then justify the three most important changes.`,keywords:keywordRoots("function single responsibility parameter return global validation exception docstring test maintainability"),minimumWords:110,hint:"Separate input, domain processing and presentation. Make dependencies explicit through parameters and return values.",explanation:"Refactoring evidence includes a concrete improved structure and a reasoned effect on testing and maintenance.",evidenceChecklist:["Revised structure","Code example","Reduced globals","Removed duplication","Improved validation/errors","Testability justified"],markScheme:["Separates responsibilities.","Replaces globals with parameters/returns.","Extracts repeated validation.","Shows credible refactored code.","Improves naming/documentation.","Explains maintainability impact.","Explains reliability impact.","Explains testing impact."],modelAnswer:"Split the program into `read_input`, `validate_record`, `analyse_records` and `display_summary`; pass data explicitly, return values, raise or handle defined exceptions, and unit-test the pure processing function.",misconception:"Suggesting comments alone as the solution to duplicated, tightly coupled code."}),
    practicalQuestion(unit,version,5,{commandWord:"Develop",difficulty:4,marks:8,responseFormat:"python",prompt:`Add file persistence to the ${context} program using CSV or JSON. Write the load and save functions, handle a missing or malformed file safely, and show how the loaded data reaches the analysis function.`,keywords:keywordRoots("import json csv open with encoding try except FileNotFoundError JSONDecodeError load dump return"),minimumWords:45,hint:"Keep storage separate from business logic and use a context manager for files.",explanation:"The solution must include real persistence code and safe error handling.",evidenceChecklist:["Load function","Save function","Context manager","Encoding/mode","Missing-file handling","Malformed-data handling","Integration call"],markScheme:["Imports a suitable library.","Uses `with open` safely.","Loads structured data.","Saves structured data.","Uses appropriate mode/encoding.","Handles missing file.","Handles malformed content.","Passes loaded data to processing code."],modelAnswer:"Use separate `load_records(path)` and `save_records(path, records)` functions with context managers. Return an empty list or a controlled error for a missing file and catch the relevant parse exception before calling the pure analysis function.",misconception:"Embedding all file operations inside the calculation loop with no exception handling."}),
  ];
  return mode==="applied"?tasks.slice(0,5):tasks;
}

function unit6PracticalTasks(unit:PearsonUnit,version:number,mode:PaperMode):LearningQuestion[]{
  const audience=["families","new learners","local employers","screen-reader users","mobile visitors","community volunteers"][Math.floor(version/2)%6];
  const context=`${version%2===0?"community arts events":"college technology showcase"} for ${audience}`;
  const tasks=[
    practicalQuestion(unit,version,0,{commandWord:"Create",difficulty:3,marks:8,responseFormat:"html_css",prompt:`Create semantic HTML for the main page of a ${context} website. Include a skip link, labelled navigation, one content section, an accessible event card and a registration form with correctly associated labels and useful input types.`,starterCode:"<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>...</title>\n</head>\n<body>\n  <!-- complete the accessible structure -->\n</body>\n</html>",keywords:keywordRoots("skip link header nav aria label main section article form label for input required button footer"),minimumWords:55,hint:"Use native semantic elements first; every form control needs a visible label.",explanation:"This task is marked through produced HTML and accessibility decisions, not a description of HTML tags.",evidenceChecklist:["Valid document shell","Skip link","Semantic landmarks","Labelled navigation","Accessible content card","Labels match input IDs","Suitable input types"],markScheme:["Complete HTML document structure.","Meaningful title and viewport.","Working skip-link target.","Header/nav/main landmarks.","Logical heading hierarchy.","Content uses an appropriate article/section.","Every control has an associated label.","Button and input types support the task."],modelAnswer:"A strong answer uses `header`, labelled `nav`, `main id=main-content`, `section/article`, and a real `form` with `label for` matching each input id. The skip link targets main content and controls use email/date/etc. types.",misconception:"Using styled `div` elements for everything and placeholder text instead of labels."}),
    practicalQuestion(unit,version,1,{commandWord:"Develop",difficulty:4,marks:8,responseFormat:"html_css",prompt:`Write responsive CSS for the ${context} page. Create a centred fluid container, an event-card grid that changes from one to three columns, visible keyboard focus, readable colour contrast and reduced-motion handling.`,starterCode:":root {\n  --brand: #0f766e;\n}\n/* complete the responsive and accessible styles */",keywords:keywordRoots("max width min grid repeat minmax media query focus visible outline contrast reduced motion"),minimumWords:45,hint:"Start mobile-first. Use Grid with `minmax`, then add only the breakpoint you genuinely need.",explanation:"Marks reward functioning CSS rules tied to responsiveness and accessibility.",evidenceChecklist:["Fluid constrained container","Mobile-first grid","Three-column breakpoint","Visible focus","Readable contrast","Reduced-motion query"],markScheme:["Creates a fluid container.","Constrains readable maximum width.","Uses a one-column base layout.","Uses Grid or Flex appropriately.","Adds a justified larger-screen breakpoint.","Defines a strong focus-visible style.","Uses accessible foreground/background colours.","Handles reduced-motion preference."],modelAnswer:"Use a width such as `min(70rem, 100% - 2rem)`, a one-column grid, and a media query setting `repeat(3, 1fr)`. Add `:focus-visible` with a high-contrast outline and disable non-essential transitions under `prefers-reduced-motion`.",misconception:"Making the page responsive only by shrinking font sizes at many arbitrary breakpoints."}),
    practicalQuestion(unit,version,2,{commandWord:"Develop",difficulty:4,marks:10,responseFormat:"javascript",prompt:`Write JavaScript for the registration form. Prevent submission, validate name and email, display field-specific messages, update an aria-live status region, and show only cards matching a selected event category. Do not use alert().`,starterCode:"const form = document.querySelector('#registration-form');\nconst status = document.querySelector('#form-status');\nconst filter = document.querySelector('#category-filter');\n\n// complete validation, feedback and filtering",keywords:keywordRoots("addEventListener submit preventDefault checkValidity setCustomValidity aria live textContent change dataset hidden filter"),minimumWords:60,hint:"Create small functions for validation and filtering, then attach event listeners.",explanation:"The task requires executable event-driven JavaScript with accessible feedback.",evidenceChecklist:["Submit listener","Default prevented","Field validation","Field-specific feedback","aria-live update","Filter change listener","Cards shown/hidden correctly"],markScheme:["Selects required DOM elements.","Handles submit event.","Prevents default submission.","Validates name.","Validates email.","Provides field-specific feedback.","Updates the live status region.","Handles filter changes.","Reads each card category safely.","Shows/hides cards correctly."],modelAnswer:"Use separate `validateForm` and `filterCards` functions. On submit, prevent default, set or render specific messages and update `status.textContent`. On filter change, compare the selected value with each card’s `dataset.category` and set `hidden`.",misconception:"Using `alert()` for all feedback or filtering only the text of the first card."}),
    practicalQuestion(unit,version,3,{commandWord:"Debug",difficulty:3,marks:8,responseFormat:"html_css",prompt:"Debug this inaccessible form fragment and provide corrected HTML/CSS: <div class=\"label\">Email</div><input id=\"mail\"><div onclick=\"send()\">Submit</div> with .field:focus { outline: none; }. Identify and fix at least six distinct problems.",keywords:keywordRoots("label for email type name autocomplete required button submit focus visible outline keyboard"),minimumWords:40,hint:"Check semantics, label association, input purpose, submission control and keyboard focus.",explanation:"Each correction should be visible in the revised code.",evidenceChecklist:["Real label","Matching for/id","Email input type","Name/autocomplete","Real button","Keyboard focus retained"],markScheme:["Uses a label element.","Associates label and input.","Uses type=email.","Adds name/autocomplete or required purpose.","Uses a real button.","Uses type=submit.","Removes click-only behaviour.","Restores visible focus."],modelAnswer:"Corrected example: `<form><label for=\"email\">Email</label><input id=\"email\" name=\"email\" type=\"email\" autocomplete=\"email\" required><button type=\"submit\">Submit</button></form>`. Use `:focus-visible { outline: 3px solid #005fcc; outline-offset: 3px; }`. The label is programmatically associated, the input communicates its purpose and validates email format, the semantic button works with keyboard and pointer input, and the visible outline preserves keyboard focus.",misconception:"Changing only colours while leaving the controls unusable by keyboard or assistive technology."}),
    practicalQuestion(unit,version,4,{commandWord:"Test",difficulty:4,marks:8,responseFormat:"test_table",prompt:`Create a website test matrix for the ${context} site. Include exact viewport/browser/device conditions, keyboard-only use, zoom, form validation, JavaScript filtering, missing images, performance and one automated accessibility check. State expected evidence and retest actions.`,keywords:keywordRoots("browser viewport device keyboard tab focus zoom validation javascript image alt performance lighthouse accessibility axe expected actual retest"),minimumWords:100,hint:"A test condition must be reproducible: name the browser, viewport, input and exact expected result.",explanation:"A useful compatibility test matrix covers functional, usability, accessibility and performance risks.",evidenceChecklist:["Browser/device conditions","Keyboard test","Zoom/reflow test","Form validation","Filtering","Image fallback/alt","Performance","Automated accessibility check"],markScheme:["Browser/viewport tests are precise.","Keyboard order and focus are tested.","Zoom/reflow is tested.","Validation behaviour is tested.","JavaScript filtering is tested.","Image/alternative text behaviour is tested.","Performance evidence is specified.","Accessibility tool and retest are specified."],modelAnswer:"Record test ID, environment, exact steps/data, expected result, actual evidence, status and retest. Include at least Chrome/Edge mobile and desktop widths, 200% zoom, keyboard-only completion, invalid email, category filter, missing image, Lighthouse performance and axe/WAVE findings.",misconception:"Writing “test on different browsers” without naming conditions, expected results or evidence."}),
    practicalQuestion(unit,version,5,{commandWord:"Evaluate",difficulty:4,marks:8,responseFormat:"written",prompt:`Evaluate the completed ${context} website against audience, purpose and client requirements. Use evidence from HTML validation, accessibility, responsive/browser testing, performance and user feedback. Prioritise two code-level improvements.`,keywords:keywordRoots("audience purpose requirements validation accessibility responsive browser performance feedback evidence improvement"),minimumWords:160,hint:"Tie every judgement to a requirement and a named piece of evidence.",explanation:"Evaluation combines technical evidence and user needs, then converts weaknesses into prioritised implementation changes.",evidenceChecklist:["Audience/purpose","Client requirements","Validation evidence","Accessibility evidence","Compatibility evidence","Performance evidence","Prioritised code improvements"],markScheme:["Evaluates audience suitability.","Evaluates purpose/client requirements.","Uses HTML/CSS validation evidence.","Uses accessibility evidence.","Uses responsive/browser evidence.","Uses performance evidence.","Prioritises a feasible code improvement.","Justifies a second improvement or overall judgement."],modelAnswer:"A developed evaluation maps requirements to test and user evidence, distinguishes confirmed strengths from assumptions, explains the effect of each weakness, and prioritises specific HTML/CSS/JavaScript changes by user impact and feasibility.",misconception:"Calling the site professional because it looks attractive without technical or user evidence."}),
  ];
  return mode==="applied"?tasks.slice(0,5):tasks;
}

export function markQuestion(question: LearningQuestion, answer: string | number) {
  return scoreQuestion(question,answer)>=Math.ceil(question.marks*.6);
}

export function scoreQuestion(question:LearningQuestion,answer:string|number){
  if(question.options)return Number(answer)===question.answer?question.marks:0;
  const normalised=String(answer).toLowerCase(), words=normalised.trim().split(/\s+/).filter(Boolean).length;
  const hits=(question.keywords??[]).filter(keyword=>normalised.includes(keyword)).length;
  const links=(normalised.match(/\b(because|therefore|however|whereas|result|evidence|requirement|consequently|although|check|test)\b/g)??[]).length;
  if(!normalised.trim())return 0;
  const depth=Math.min(1,words/(question.minimumWords??30)),knowledge=Math.min(1,hits/Math.max(1,Math.min(3,question.keywords?.length??1))),reasoning=Math.min(1,links/(question.difficulty>=3?2:1));
  return Math.min(question.marks,Math.round(question.marks*(depth*.35+knowledge*.35+reasoning*.3)));
}

export function levelDifficulty(level: ExpertiseLevel) { return level === "Support" ? 1 : level === "Core" ? 2 : level === "Stretch" ? 3 : 4; }
export function nextDifficulty(current:number,correct:boolean){return Math.max(1,Math.min(4,current+(correct?1:-1)));}
export function orderByTargetDifficulty(questions:LearningQuestion[],target:number){return [...questions].sort((a,b)=>Math.abs(a.difficulty-target)-Math.abs(b.difficulty-target)||a.difficulty-b.difficulty);}

function appliedMarkScheme(concept:string,marks:number){return Array.from({length:marks},(_,index)=>index===0?`Accurate use of ${concept}.`:index===1?"Application to the named context.":index===2?"A developed reason or consequence.":`Further relevant development or evidence (${index+1}).`);}
function modelResponse(context:string,first:string,second:string,command:string){return `${context} should apply ${first} because this directly addresses the stated requirement. It should also consider ${second}; the result can be checked against a measurable success criterion. For a ${command.toLowerCase()} response, the final decision should follow from the evidence and acknowledge a realistic limitation or alternative.`;}
function keywordRoots(value:string){return unique(value.toLowerCase().split(/[^a-z0-9]+/).filter(word=>word.length>4)).slice(0,8);}
function unique<T>(values:T[]){return [...new Set(values)];}
function shuffleStable(values:string[],seed:number){return values.map((value,index)=>({value,rank:(index*7+seed*3)%values.length})).sort((a,b)=>a.rank-b.rank).map(item=>item.value);}
