import {describe,expect,it} from "vitest";
import {configuredUnits} from "./learning-catalog";
import {markQuestion,nextDifficulty,orderByTargetDifficulty,paperBlueprintsFor,paperQuestions,questionsFor,scoreQuestion} from "./atom-question-bank";

describe("Atom-style BTEC question bank",()=>{
 it("covers every configured Pearson topic with hints and explanations",()=>{
  expect(configuredUnits.map(unit=>unit.code)).toEqual(["1","2","4","6","8","9","10","14"]);
  expect(configuredUnits.reduce((sum,unit)=>sum+unit.topics.length,0)).toBe(62);
  expect(configuredUnits.flatMap(unit=>unit.topics.map(topic=>questionsFor(unit,topic))).flat()).toHaveLength(496);
  for(const unit of configuredUnits)for(const topic of unit.topics){const questions=questionsFor(unit,topic);expect(questions).toHaveLength(8);expect(questions.every(item=>item.hint&&item.explanation&&item.modelAnswer&&item.misconception)).toBe(true);expect(questions.every(item=>item.markScheme.length>0&&item.markScheme.length<=item.marks)).toBe(true);expect(questions.some(item=>item.options)).toBe(true);expect(questions.some(item=>item.kind==="extended_response")).toBe(true);expect(new Set(questions.map(item=>item.commandWord))).toEqual(new Set(["Identify","Describe","Explain","Analyse","Justify","Evaluate"]));}
 });
  it("builds three assessment-appropriate paper types",()=>{for(const unit of configuredUnits){const blueprints=paperBlueprintsFor(unit);expect(blueprints.map(item=>item.mode)).toEqual(["knowledge","applied","assignment"]);expect(paperQuestions(unit,0,"knowledge")).toHaveLength(unit.topics.length*2);const applied=paperQuestions(unit,0,"applied"),assignment=paperQuestions(unit,0,"assignment");if(["2","4","6"].includes(unit.code)){expect(applied.every(item=>item.kind==="practical_response")).toBe(true);expect(assignment.every(item=>item.kind==="practical_response")).toBe(true);expect(new Set(assignment.map(item=>item.id)).size).toBe(assignment.length)}else{expect(applied).toHaveLength(unit.topics.length*2);expect(assignment).toHaveLength(unit.topics.length);expect(new Set(assignment.map(item=>item.id)).size).toBe(unit.topics.length)}}});
  it("labels Unit 14 as external set-task preparation, never an internal assignment",()=>{const unit=configuredUnits.find(item=>item.code==="14")!,paper=paperBlueprintsFor(unit).find(item=>item.mode==="assignment")!;expect(paper.title).toContain("set-task");expect(paper.description).toContain("not Pearson's live task")});
 it("mirrors the practical evidence expected in the Unit 2 external set task",()=>{const unit=configuredUnits.find(item=>item.code==="2")!,tasks=paperQuestions(unit,0,"assignment");expect(tasks).toHaveLength(8);expect(tasks.reduce((sum,item)=>sum+item.marks,0)).toBe(66);expect(tasks.map(item=>item.responseFormat)).toEqual(expect.arrayContaining(["database_design","sql","test_table","written"]));expect(tasks.map(item=>item.commandWord)).toEqual(expect.arrayContaining(["Normalise","Create","Develop","Test","Evaluate"]));expect(tasks.map(item=>item.prompt).join(" ")).toMatch(/UNF/);expect(tasks.map(item=>item.prompt).join(" ")).toMatch(/1NF/);expect(tasks.map(item=>item.prompt).join(" ")).toMatch(/2NF/);expect(tasks.map(item=>item.prompt).join(" ")).toMatch(/3NF/);expect(tasks.map(item=>item.prompt).join(" ").toLowerCase()).toMatch(/form/);expect(tasks.map(item=>item.prompt).join(" ").toLowerCase()).toMatch(/quer/);expect(tasks.map(item=>item.prompt).join(" ").toLowerCase()).toMatch(/validation/)});
 it("requires produced code and testing evidence in Units 4 and 6",()=>{for(const code of ["4","6"]){const unit=configuredUnits.find(item=>item.code===code)!,tasks=paperQuestions(unit,0,"assignment");expect(tasks).toHaveLength(6);expect(tasks.every(item=>item.evidenceChecklist?.length)).toBe(true);expect(tasks.map(item=>item.responseFormat)).toContain(code==="4"?"python":"javascript");expect(tasks.map(item=>item.responseFormat)).toContain("test_table");expect(tasks.map(item=>item.commandWord)).toEqual(expect.arrayContaining(["Develop","Debug","Test","Evaluate"]))}});
 it("gives every practical mark an explicit rubric point and a substantive accurate model",()=>{for(const code of ["2","4","6"]){const unit=configuredUnits.find(item=>item.code===code)!;for(const version of [0,1])for(const task of paperQuestions(unit,version,"assignment")){expect(task.markScheme,task.id).toHaveLength(task.marks);expect(task.evidenceChecklist?.length,task.id).toBeGreaterThanOrEqual(5);expect(task.modelAnswer.split(/\s+/).length,task.id).toBeGreaterThanOrEqual(20);expect(task.prompt,task.id).not.toMatch(/undefined/i)}}});
 it("keeps every objective answer index valid, unique and equal to its model answer",()=>{for(const unit of configuredUnits)for(const topic of unit.topics)for(const question of questionsFor(unit,topic).filter(item=>item.options)){expect(new Set(question.options).size,question.id).toBe(question.options!.length);expect(question.answer,question.id).toBeGreaterThanOrEqual(0);expect(question.answer,question.id).toBeLessThan(question.options!.length);expect(question.modelAnswer,question.id).toBe(question.options![question.answer!])}});
 it("generates comparable practical versions with changed scenarios and stable mark totals",()=>{for(const code of ["2","4","6"]){const unit=configuredUnits.find(item=>item.code===code)!,first=paperQuestions(unit,0,"assignment"),second=paperQuestions(unit,1,"assignment");expect(second.map(item=>item.prompt)).not.toEqual(first.map(item=>item.prompt));expect(second.reduce((sum,item)=>sum+item.marks,0)).toBe(first.reduce((sum,item)=>sum+item.marks,0))}});
 it("keeps six consecutive practical papers meaningfully distinct",()=>{for(const code of ["2","4","6"]){const unit=configuredUnits.find(item=>item.code===code)!;const signatures=Array.from({length:6},(_,version)=>paperQuestions(unit,version,"assignment").map(item=>item.prompt).join("\n"));expect(new Set(signatures).size,`Unit ${code}`).toBe(6);const totals=Array.from({length:6},(_,version)=>paperQuestions(unit,version,"assignment").reduce((sum,item)=>sum+item.marks,0));expect(new Set(totals).size).toBe(1)}});
 it("marks objective answers deterministically",()=>{const question=questionsFor(configuredUnits[0],configuredUnits[0].topics[0])[0];expect(markQuestion(question,question.answer??-1)).toBe(true);expect(markQuestion(question,99)).toBe(false)});
 it("awards graduated indicative marks to written responses",()=>{const question=questionsFor(configuredUnits[1],configuredUnits[1].topics[0])[5];expect(scoreQuestion(question,"")).toBe(0);const partial=scoreQuestion(question,`The organisation should consider ${question.keywords?.[0]} because it affects the requirement.`);expect(partial).toBeGreaterThan(0);expect(partial).toBeLessThan(question.marks);const developed=`${question.keywords?.join(" ")} because this meets the requirement and therefore improves the result. However, the organisation should test the outcome as evidence. `.repeat(8);expect(scoreQuestion(question,developed)).toBe(question.marks)});
 it("moves difficulty up after success and down after an error",()=>{expect(nextDifficulty(2,true)).toBe(3);expect(nextDifficulty(3,false)).toBe(2);expect(nextDifficulty(4,true)).toBe(4);expect(nextDifficulty(1,false)).toBe(1);const questions=questionsFor(configuredUnits[0],configuredUnits[0].topics[0]);expect(orderByTargetDifficulty(questions,4)[0].difficulty).toBe(4)});
});
