import type { PearsonTopic, PearsonUnit } from "./pearson-curriculum";

// Original teaching outlines mapped to Pearson BTEC National IT (2016), Issue 6.
// These are formative learning resources, not Pearson assignment briefs or live tasks.
export const pearsonSpecificationSource = "https://qualifications.pearson.com/content/dam/pdf/BTEC-Nationals/Information-Technology/2016/specification-and-sample-assessments/specification-pearson-btec-level-3-national-extended-diploma-in-information-technology.pdf";
function topic(code: string, title: string, content: string[], scenario: string, outcome: string): PearsonTopic {
  return { code, title, content, phases: [
    {label:"Explain",detail:`Understand ${title.toLowerCase()} using the example before attempting independent work.`},
    {label:"Worked examples",detail:scenario},
    {label:"Practice",detail:outcome},
    {label:"Challenge",detail:"Compare another approach, identify its limitations and defend your recommendation using evidence."},
    {label:"Assignment goal",detail:outcome},
  ]};
}
export const extendedPearsonUnits: PearsonUnit[] = [
  {code:"5",title:"Data Modelling",assessment:"Internally assessed. Investigate decision-making with spreadsheet models, then design, develop, test and evaluate a model against the teacher's assignment brief.",topics:[
    topic("A1-A2","Decisions and spreadsheet tools",["reliable and current information","spreadsheet formulae and functions","input validation and clear outputs"],"A community café needs to decide whether longer opening hours will cover staff and energy costs. Separate facts from estimates before calculating the result.","Explain how a spreadsheet helps a client make a decision, including the effect of unreliable assumptions."),
    topic("A3-A5","Alternatives and justified decisions",["what-if inputs and alternative outcomes","model assumptions and limitations","documented decisions with supporting evidence"],"Compare the café opening for one, two or three extra hours. A higher sales forecast is not guaranteed income; show how the recommendation changes when demand falls.","Evaluate alternatives and justify a recommendation without treating a prediction as a fact."),
    topic("B1","Define the model's requirements",["functional specification and user needs","constraints and measurable success criteria","inputs processing and outputs"],"The manager must change hourly sales and staffing costs without editing formulae. Specify a break-even output and a clear warning when a scenario makes a loss.","Write requirements that can each be checked against a test result."),
    topic("B2-B3","Design and review the spreadsheet",["worksheet layouts and navigation","formula and validation design","test planning and client feedback"],"Sketch an Inputs sheet and a Results sheet. Ask a colleague to find the daily profit and identify which assumptions they can change, then revise confusing labels.","Produce a reviewable design and record why feedback changed it."),
    topic("C1","Build the spreadsheet model",["relative absolute and cross-sheet references","logical lookup and summary functions","sorting filtering pivoting import and export","protected inputs macros and accessible controls"],"Calculate revenue minus variable and fixed costs. Keep the hourly rate in one fixed-reference cell so copying a formula does not change the reference accidentally.","Build a working spreadsheet with traceable calculations and safe data entry."),
    topic("C2","Test calculations and usability",["normal boundary and invalid input tests","independent expected results","correctness functionality and user acceptance"],"For 20 sales at £4 and £50 total costs, independently calculate £30 profit. Compare this with the spreadsheet, then test zero sales and an invalid negative quantity.","Record expected and actual results, fix defects and repeat the failed tests."),
    topic("C3-C4","Improve and evaluate the model",["feedback-led optimisation","fitness for client requirements","professional communication and reflection"],"Users repeatedly overwrite a formula. Lock calculated cells, retain editable input cells and retest with the same users before claiming an improvement.","Evaluate the final model using test evidence, client needs and your documented development decisions."),
  ]},
  {code:"11",title:"Cyber Security and Incident Management",assessment:"Externally assessed by a Pearson-set supervised task. Portal activities are original formative preparation, not the live assessment and not internal assignment grades.",topics:[
    topic("A1-A2","Threats, vulnerabilities and impact",["internal and external security threats","technical human and physical vulnerabilities","operational financial reputational and data loss"],"A fictional charity has a shared administrator password and an unpatched laptop. Distinguish the weakness from an attacker exploiting it and explain which services could be interrupted.","Trace a plausible threat through a specific weakness to a justified business impact."),
    topic("A3-A5","Protection and responsibilities",["authorisation privacy and lawful handling of information","physical controls backups and recovery","authentication access control firewalls and malware protection","encryption certificates and wireless protection"],"The charity needs volunteers to access bookings but not payroll. Use separate accounts and restricted permissions; add recovery-tested backups because access controls cannot prevent every failure.","Choose layered controls for named risks, explain limitations and consult current authoritative legal guidance."),
    topic("B1-B2","Network architecture and components",["network types topologies and client-server models","endpoints switches routers and connection media","virtualisation cloud and monitoring tools"],"Draw separate staff and guest networks for a community centre. Explain what each router, switch and access point does, and why guest devices should not reach staff records.","Interpret a network diagram and justify defensive design choices. Work only in authorised teaching environments."),
    topic("B3","Network services and segmentation",["TCP/IP addressing ports packets and NAT","DNS DHCP directory and authentication services","segmentation routing and remote access"],"A device receives an address from DHCP but cannot resolve a hostname. Separate addressing, name resolution and permission checks rather than assuming every failure is an attack.","Explain how a service works and identify where a specific control limits exposure."),
    topic("C1-C2","Assess vulnerabilities and prioritise risks",["authorised vulnerability assessment and independent review","likelihood impact and risk severity","evidence-based risk prioritisation"],"Use a supplied fictional scan report: one finding affects a public booking server, another affects a disconnected training device. Justify priority using exposure and impact, not only the number of findings.","Produce a contextual risk assessment. Do not scan public or college systems without explicit permission."),
    topic("C3","Design and test a protection plan",["risk treatment and proportionate controls","cost usability technical constraints and residual risk","security test plans with expected outcomes"],"Propose stronger sign-in and restricted payroll access. Test that an authorised payroll user succeeds and a volunteer is denied; record recovery arrangements if sign-in fails.","Link each risk to a control, justification, test and remaining limitation."),
    topic("D1-D2","Policies, response and recovery",["security policies training and audit","incident roles reporting containment and recovery","recovery time and recovery point objectives","supplier agreements responsibilities and exit plans"],"A fictional ransomware alert arrives during opening hours. Identify who coordinates the response, which service is critical, what evidence must be preserved and which verified backup can support recovery.","Write a usable response and recovery plan with clear ownership and evidence-based priorities."),
    topic("E1-E2","Preserve and analyse incident evidence",["authorised forensic collection and evidence integrity","system network and user activity timelines","reliability alternative explanations and false positives","supported conclusions and prevention recommendations"],"A supplied log shows a failed login followed by a successful login. Correlate timestamps and other evidence; the two entries alone do not prove account theft. Preserve originals and analyse copies.","Build a defensible incident timeline, distinguish observations from inference and justify improvements."),
  ]},
  {code:"16",title:"Cloud Storage and Collaboration Tools",assessment:"Internally assessed. Investigate cloud options, then design, deploy, manage and evaluate a collaboration solution against the teacher's assignment brief.",topics:[
    topic("A1-A2","Cloud services and delivery models",["on-demand access elasticity shared resources and measured use","SaaS PaaS and IaaS responsibilities","public private hybrid and community cloud"],"A charity wants volunteers to edit documents together. Compare using a hosted document application with maintaining a virtual server: both use cloud resources, but the charity manages different responsibilities.","Explain and compare cloud models using the organisation's actual needs."),
    topic("A3-A5","Requirements, impact and responsibilities",["business needs infrastructure and bandwidth","cost accessibility staffing and migration","data ownership privacy licensing jurisdiction and exit arrangements"],"Some volunteers use older phones and unreliable connections. Test access and plan offline working before choosing a service; check who owns the data and how it can be exported.","Evaluate suitability and constraints, checking current provider terms and authoritative legal guidance."),
    topic("B1-B2","Plan and review a collaboration service",["client and technical requirements","roles permissions storage and test planning","review feedback and revised designs"],"Plan folders for public resources, volunteer rotas and confidential staff files. Use a permissions table to show who may read, edit or share each area, and review it with the client.","Produce a justified design with testable access rules and recorded feedback."),
    topic("B3","Deploy and configure the service",["service and client configuration","accounts quotas privileges and access rights","collaboration protocols and deployment records"],"In a teacher-approved sandbox, create a shared workspace, give a test volunteer editing rights to the rota only and verify that removing access prevents further use.","Deploy the agreed service in an authorised environment and retain configuration evidence without exposing credentials."),
    topic("C1-C2","Test, maintain and refine",["functional user performance and security tests","monitoring updates compatibility and changing needs","backup recovery and feedback-led improvements"],"Test simultaneous edits, a revoked user, a broken connection and restoration of a deleted test file. Record what happened rather than assuming that synchronisation is a backup.","Use reproducible tests and monitoring evidence to correct faults and improve reliability."),
    topic("C3-C5","Evaluate and hand over the service",["evaluation against client requirements","clear user guidance and presentation","lessons learned and professional reflection"],"Demonstrate a realistic collaboration task to the client, explain a remaining limitation and hand over account-management and recovery instructions suited to the user's technical confidence.","Evaluate the delivered service and your working process using specific evidence and justified improvements."),
  ]},
];
