import {makeStudyPack} from "./mini-study-pack";
import {unit4ExtensionIdeas} from "./mini-study-unit4-extension";

// Keep lesson identities stable: completed steps and saved answer keys remain intact.
export const programmingStudy=makeStudyPack("4",[
 {id:"decompose",topic:"A1",title:"Break the problem into parts",skill:"decomposition",
 lines:["Decomposition divides a problem into smaller manageable parts.","Give each part a clear job, then decide what information the parts share.","You still need to check that the parts work together."],
 example:"A college canteen app takes an order, calculates the total and sends it to the kitchen. If the total is wrong, you can investigate the calculation without changing how the kitchen receives orders.",
 help:"Describe the jobs first. Then consider which information passes between them.",
 question:"A canteen app shows the wrong total but sends the right items to the kitchen. Which part would you investigate first?",
 answers:["The calculation that adds up item prices","The code that sends item names to the kitchen","The screen that lists collection times"],
 feedback:"The reported fault is in the total. Start with the calculation and the prices passed into it, then check how it connects to the rest of the app.",
 pairs:[["Decomposition","Separating ordering, pricing and kitchen messages"],["Integration","Checking that an order passes correctly between those parts"]],
 analyse:"Separate pricing code makes a calculation fault easier to investigate, although incorrect input from another part can still cause a wrong total.",
 evaluate:"Choose boundaries that make sense for the task. Test the connections as well as each individual part.",
 baselineCheck:{question:"You are planning a library app. Which plan breaks the job into useful parts?",answers:["Find a book, check availability, then record the loan","Write the entire app before deciding what it needs to do","Split the code into equal-sized files regardless of their jobs"],feedback:"These parts have distinct responsibilities. Dividing code by file size alone does not separate the problem meaningfully."},
 recapCheck:{question:"A bus app has separate functions for finding a route and calculating its fare. What still needs checking?",answers:["That the selected route is passed correctly to the fare function","Only that both functions have the same number of lines","Only that each function runs on its own"],feedback:"Working parts can still be connected incorrectly. Check the information passed between them."}},
 {id:"variables",topic:"A1",title:"A value can change",skill:"variables",
 lines:["A variable stores a value that can change while a program runs.","A constant represents a value intended to stay fixed.","A useful name tells the reader what the value represents."],
 example:"A booking app starts with seats_left = 12. After someone books two seats, it updates seats_left = seats_left - 2. The remaining capacity is now 10; the venue's total capacity has not changed.",
 help:"Use the value on the right-hand side first, then store the result under the name on the left.",
 question:"There are 12 seats left. A booking takes two, then another takes one. What should seats_left contain?",
 answers:["9","10","11"],feedback:"The updates happen in order: 12 becomes 10, then 10 becomes 9. Use the updated value for the second booking.",
 pairs:[["seats_left","Changes as bookings are made or cancelled"],["venue_capacity","Stays fixed for this venue during the booking session"]],
 analyse:"Keeping remaining seats separate from total capacity helps the program handle bookings without losing the original limit.",
 evaluate:"Check bookings and cancellations, including attempts to book more seats than remain. A clear name alone cannot prevent an incorrect update.",
 baselineCheck:{question:"A music player moves to a different track. Which stored value needs updating?",answers:["The current track title","The maximum volume allowed by its settings","The installed app version"],feedback:"The current track changes during playback. The other values do not change simply because a different track starts."},
 recapCheck:{question:"A shop has stock = 8. Two returned items are added with stock = stock + 2. What is stored now?",answers:["10","6","2"],feedback:"Add the two returned items to the existing eight. The new stored value is 10."}},
 {id:"selection",topic:"A4–A6",title:"Choose a path using a condition",skill:"selection",
 lines:["Selection uses a true-or-false condition to choose what happens next.","The comparison operator determines whether the boundary is included.","Check examples below, at and above that boundary."],
 example:"A delivery service charges £2 when an order is below £20. Its rule is: if order_total >= 20, delivery is free; otherwise, charge £2. An order of exactly £20 qualifies for free delivery.",
 help:"Read >= as greater than or equal to. The equal-to part matters at the exact boundary.",
 question:"The free-delivery rule is order_total >= 20. What happens to an order worth exactly £20?",
 answers:["Delivery is free","A £2 delivery charge is added","Neither branch runs"],feedback:"20 >= 20 is true, so the free-delivery branch runs. Using > instead would treat exactly £20 differently.",
 pairs:[[">= 20","Includes an order worth exactly £20"],["> 20","Requires an order worth more than £20"]],
 analyse:"Changing >= to > would charge customers at the exact free-delivery threshold. Most other test orders would not reveal that mistake.",
 evaluate:"Try £19.99, £20 and £20.01, with expected results written down first. A single successful order is not enough to check the boundary.",
 baselineCheck:{question:"A heater turns on when temperature < 18. The temperature is 16. Which action follows the rule?",answers:["Turn the heater on","Keep the heater off","Wait until the temperature is exactly 18"],feedback:"16 is below 18, so the condition is true and the heater turns on."},
 recapCheck:{question:"A file is accepted when size_mb <= 5. Which pair checks the allowed limit and a value just over it?",answers:["5 MB and 5.1 MB","1 MB and 2 MB","6 MB and 7 MB"],feedback:"5 MB is accepted at the boundary; 5.1 MB is rejected just above it. The other pairs stay on one side."}},
 {id:"iteration",topic:"A4–A6",title:"Repeat with a stopping rule",skill:"iteration",
 lines:["A loop repeats instructions.","Check what changes each time and when the loop stops.","A trace records those changes one step at a time."],
 example:"A printer has four labels to print. After printing a label, it subtracts one from labels_left. The loop continues while labels_left > 0, so it should stop after the fourth label.",
 help:"Write down labels_left after each print: 4 becomes 3, then 2, then 1, then 0.",
 question:"The printer keeps printing the first label. Its loop runs while labels_left > 0, but labels_left never changes. What is missing?",
 answers:["An update that reduces labels_left after each print","A reset of labels_left to 4 after each print","A change from > 0 to >= 0 without updating labels_left"],feedback:"The value must move towards the stopping condition. Resetting it or including zero does not fix the missing update.",
 pairs:[["Loop condition","Checks whether any labels remain"],["Loop update","Subtracts one after a label is printed"]],
 analyse:"A missing update can keep a condition true indefinitely, wasting paper and preventing the job from finishing.",
 evaluate:"Check an empty job, one label and several labels. Confirm both the number printed and that the program stops.",
 baselineCheck:{question:"A playlist should play each saved track once. Which approach still works when another track is added?",answers:["Loop through the tracks in the playlist","Write a separate play command for each existing track and leave the code unchanged","Keep repeating only the first track"],feedback:"A loop over the collection can process the added track without another individually written command."},
 recapCheck:{question:"An email app loops through a list of unread messages. The list is empty. How many message previews should this loop create?",answers:["None","One empty preview","The same number as yesterday"],feedback:"A loop over an empty collection processes no items. There is no unread message to preview."}},
 ...unit4ExtensionIdeas,
]);
