import type {ShortStudyIdea} from "./mini-study-pack";

/** Additional Unit 2 steps covering the rest of the Pearson topic map. */
export const unit2ExtensionIdeas: ShortStudyIdea[] = [
  {id:"relational-operations",topic:"A1",title:"Use relational operations to find the right data",skill:"relational-operations",
    lines:["Relational operations combine or filter sets of records.","Select filters rows, while a join combines related rows from tables.","Union and intersect compare compatible sets."],
    example:"A college stores Students and Enrolments separately. Joining them can show each student's course without repeating student details in every enrolment row.",
    help:"Ask whether the task needs fewer rows, columns from another table, or a comparison between two compatible sets.",
    question:"Which operation combines related Student and Enrolment rows?",answers:["Join","Delete","Rename the database file"],feedback:"A join combines related rows using matching values such as StudentID.",
    pairs:[["Select","Filters rows that meet a condition"],["Join","Combines related rows from tables"]],
    analyse:"A join avoids copying the student's name into every enrolment record, reducing duplication.",evaluate:"Check that join fields use compatible keys and that the result answers the user's question without accidental duplicates."},
  {id:"domains-integrity",topic:"A1",title:"Protect valid relationships and values",skill:"integrity",
    lines:["A domain defines the allowed kind or range of values for an attribute.","Entity integrity protects primary keys.","Referential integrity prevents a foreign key pointing to a missing parent record."],
    example:"A Loan cannot refer to MemberID 900 if no member 900 exists. A ReturnDate field may also allow null until the item is returned.",
    help:"Check the value rule first, then check whether referenced records actually exist.",
    question:"Which rule stops a loan referring to a member who does not exist?",answers:["Referential integrity","A decorative report title","Changing the table colour"],feedback:"Referential integrity checks that a foreign-key reference matches an existing parent key.",
    pairs:[["Domain","Allowed values for an attribute"],["Referential integrity","Validates references between related records"]],
    analyse:"Integrity rules stop structurally inconsistent data entering the system before reports depend on it.",evaluate:"Use realistic invalid test data as well as valid data before claiming that integrity controls are effective."},
  {id:"sql-crud",topic:"A2",title:"Create, read, update and delete data safely",skill:"sql",
    lines:["SQL can define structures and manipulate stored data.","INSERT adds rows, UPDATE changes matching rows and DELETE removes matching rows.","A WHERE condition matters because an unrestricted change can affect many rows."],
    example:"UPDATE Loans SET Returned = true WHERE LoanID = 42 changes one intended loan. Omitting the WHERE condition could change every loan.",
    help:"Before running a change, say which rows should be affected and how the condition identifies them.",
    question:"What is the main risk of an UPDATE statement with no WHERE condition?",answers:["It may update every row in the table","It automatically creates a backup","It changes only the first row"],feedback:"Without a limiting condition, an UPDATE can affect all rows in the target table.",
    pairs:[["INSERT","Adds a new row"],["UPDATE","Changes existing matching rows"]],
    analyse:"A precise condition reduces the chance that one maintenance task damages unrelated records.",evaluate:"Use permissions, backups and a tested condition before running high-impact changes on important data."},
  {id:"queries-reports",topic:"A2",title:"Turn stored data into useful information",skill:"querying",
    lines:["A query retrieves data that matches a question.","Criteria can combine conditions, calculations and multiple tables.","Reports present selected results in a form suitable for the audience."],
    example:"A manager wants overdue loans grouped by course. The query finds overdue rows; the report presents counts and details clearly.",
    help:"Write the user's question in plain English before choosing fields and criteria.",
    question:"What should determine the fields and criteria in a query?",answers:["The information the user needs","The designer's favourite field names","The number of colours in the report"],feedback:"Queries should be designed from the information requirement, then checked against expected results.",
    pairs:[["Query","Retrieves or calculates selected data"],["Report","Presents results for an audience"]],
    analyse:"Separating retrieval from presentation lets the same reliable query support several report layouts.",evaluate:"Verify the underlying query before judging the report accurate; a polished layout cannot repair incorrect criteria."},
  {id:"security-recovery",topic:"A2",title:"Control access and plan recovery",skill:"security",
    lines:["Database users should receive only the permissions they need.","Authentication identifies the user; authorisation controls what that user may do.","Backups and tested recovery reduce the impact of loss or corruption."],
    example:"Reception staff may add bookings but not change staff payroll data. An administrator can restore a verified backup after an accidental deletion.",
    help:"Think about least privilege, then ask how the service would recover if a permitted action still caused damage.",
    question:"Which approach best protects payroll data from ordinary reception accounts?",answers:["Restrict their permissions to the tasks they need","Give every account full administrator access","Use the same shared password for everyone"],feedback:"Least privilege limits what an account can change and reduces the impact of mistakes or compromise.",
    pairs:[["Authentication","Checks who the user is"],["Authorisation","Controls what the user may do"]],
    analyse:"Separate permissions reduce the damage one compromised or mistaken account can cause.",evaluate:"Access control is only one layer; recovery, audit and secure account management still need testing."},
  {id:"anomalies",topic:"A3",title:"Spot update, insertion and deletion anomalies",skill:"anomalies",
    lines:["Poorly structured tables can repeat the same fact many times.","An update anomaly occurs when repeated copies become inconsistent.","Insertion and deletion anomalies make it difficult to add or remove one fact without affecting another."],
    example:"A table repeats a tutor's phone number on every student row. Changing only some copies creates conflicting numbers.",
    help:"Look for facts that describe different things but are stored together repeatedly.",
    question:"What is an update anomaly?",answers:["Repeated copies of the same fact can become inconsistent","Every update is automatically rejected","A report contains too many headings"],feedback:"Repeated facts create a risk that only some copies are changed.",
    pairs:[["Update anomaly","Repeated copies can disagree after a change"],["Deletion anomaly","Removing one record can accidentally remove another needed fact"]],
    analyse:"Separating tutor details from student records gives the tutor phone number one authoritative place to change.",evaluate:"Normalisation should reduce anomalies while still supporting the organisation's real queries and performance needs."},
  {id:"normalise-1nf",topic:"A3",title:"Move repeating groups into first normal form",skill:"normalisation",
    lines:["First normal form requires each field to hold one atomic value for the design being used.","Repeating groups such as Item1, Item2 and Item3 should become separate rows or a related table.","A key must identify each resulting record."],
    example:"An Order row with Product1, Product2 and Product3 can be separated into Orders and OrderLines, one line per product on the order.",
    help:"If the design needs another numbered column whenever one more item appears, look for a repeating group.",
    question:"Which design best handles any number of products on an order?",answers:["A related OrderLines table with one row per product","Product1 to Product20 columns","A single field containing several product names separated by commas"],feedback:"A related table removes the fixed repeating group and supports any number of order lines.",
    pairs:[["1NF","Removes repeating groups into atomic values"],["Composite key","Uses more than one field together to identify a record"]],
    analyse:"OrderLines can grow without changing the table structure each time an order contains more products.",evaluate:"State the key and relationship clearly so the normalised structure can be implemented without ambiguity."},
  {id:"normalise-2nf-3nf",topic:"A3",title:"Remove partial and transitive dependencies",skill:"normalisation",
    lines:["Second normal form removes non-key attributes that depend on only part of a composite key.","Third normal form removes non-key attributes that depend on another non-key attribute.","The goal is to store each fact with the key that determines it."],
    example:"In OrderLines, ProductName depends on ProductID rather than on the whole OrderID plus ProductID key, so product details belong in Products.",
    help:"Ask: what determines this value? If it is not the whole key, the attribute may belong elsewhere.",
    question:"ProductName is determined by ProductID. Where should ProductName normally be stored?",answers:["In the Products table keyed by ProductID","Repeated in every order line","Inside the OrderID field"],feedback:"Store product facts with the product key that determines them, then reference that product from order lines.",
    pairs:[["2NF","Removes partial dependency on part of a composite key"],["3NF","Removes dependency between non-key attributes"]],
    analyse:"Removing dependencies reduces duplicated facts and makes later updates more reliable.",evaluate:"Explain each functional dependency rather than claiming a design is 3NF simply because it has several tables."},
  {id:"conceptual-logical-physical",topic:"B1",title:"Move from client need to physical database",skill:"design",
    lines:["A conceptual model identifies important entities and relationships.","A logical model adds attributes, keys and normalised structure.","A physical design turns that logic into actual tables, data types, indexes and platform choices."],
    example:"A booking system begins with Customer, Booking and Room entities, then adds keys and attributes before choosing concrete SQL data types.",
    help:"Do not jump to field sizes before the entities and relationships make sense.",
    question:"Which stage normally adds actual platform-specific data types and indexes?",answers:["Physical design","Conceptual modelling","Writing the project title"],feedback:"Physical design translates the logical model into implementation details for the chosen RDBMS.",
    pairs:[["Conceptual model","High-level entities and relationships"],["Physical design","Implementation details for the chosen system"]],
    analyse:"Separating these stages lets the team check the business model before committing to technical details.",evaluate:"The final physical design should still trace back to the client requirements and normalised logical model."},
  {id:"data-dictionary",topic:"B2",title:"Write a data dictionary another developer can use",skill:"documentation",
    lines:["A data dictionary describes fields consistently.","Useful entries include name, purpose, type, size, validation, key role and whether null is allowed.","Naming conventions reduce ambiguity across tables, forms and queries."],
    example:"DateOfBirth: date, required, must not be in the future, used to calculate age only when needed.",
    help:"Imagine another developer must build the field without asking you a question.",
    question:"Which detail belongs in a useful data dictionary?",answers:["The field's type and validation rule","Only the developer's initials","The colour of the office wall"],feedback:"Implementation needs explicit field properties, rules and purpose.",
    pairs:[["Data dictionary","Defines fields and their rules"],["Naming convention","Keeps identifiers consistent and understandable"]],
    analyse:"Precise documentation reduces inconsistent implementations when several forms and queries use the same field.",evaluate:"Review the dictionary against the ERD and requirements so no field or rule is undocumented."},
  {id:"interfaces-validation",topic:"B2",title:"Design forms that prevent avoidable mistakes",skill:"validation",
    lines:["Forms should match the user's task and reduce unnecessary entry.","Validation rules reject values that do not meet known constraints.","Verification and clear feedback help users correct mistakes rather than simply blocking them."],
    example:"A booking form uses a date control, requires a customer, and explains why an end date cannot be before a start date.",
    help:"For each field, ask what can be known to be invalid and what message would help the user fix it.",
    question:"Which message best helps after an invalid end date?",answers:["End date must be on or after the start date","Error 27","Something went wrong"],feedback:"Specific feedback states the rule and gives the user a clear correction path.",
    pairs:[["Validation rule","Rejects data outside an allowed rule"],["Verification","Checks entered data against its source"]],
    analyse:"Clear validation reduces bad data without forcing staff to guess why an entry failed.",evaluate:"Test valid, boundary and invalid inputs with realistic users before judging the form effective."},
  {id:"forms-automation",topic:"C1",title:"Build forms, queries and safe automation",skill:"implementation",
    lines:["A working solution combines tables, relationships, forms, queries and reports.","Automation should remove repetitive work without hiding important decisions.","Every automated action needs a clear trigger, expected result and failure check."],
    example:"A button creates a standard overdue-loan report from a tested query instead of asking staff to rebuild the criteria each week.",
    help:"Automate a repeatable rule, not a judgement that still needs a person.",
    question:"Which task is a good candidate for safe automation?",answers:["Running the same tested overdue query and report","Deleting every old record without review","Changing user permissions at random"],feedback:"A stable, repeatable rule can be automated and then tested against expected results.",
    pairs:[["Form","Interface for viewing or entering records"],["Automation","A repeatable action triggered by a defined rule or event"]],
    analyse:"Automation can reduce inconsistent manual steps when the underlying query and trigger are reliable.",evaluate:"Keep an audit trail and test failure cases before relying on automation for important operations."},
  {id:"test-and-refine",topic:"C2",title:"Test normal, extreme and erroneous data",skill:"testing",
    lines:["A test plan states what is being checked, the input, expected result and actual result.","Normal data checks ordinary use, extreme data checks boundaries and erroneous data checks invalid input.","Failed tests should lead to a fix and a recorded retest."],
    example:"If quantity must be 1 to 10, test 5, then 1 and 10, then 0 and 11. Record what should happen before running each test.",
    help:"Write the expected result independently so the test does not simply copy what the database already did.",
    question:"What should happen after a failed test is fixed?",answers:["Run the relevant test again and record the new result","Delete the failed test from the plan","Assume every other feature is now correct"],feedback:"Retesting provides evidence that the specific defect was actually corrected.",
    pairs:[["Extreme data","Values at important valid boundaries"],["Erroneous data","Values that should be rejected"]],
    analyse:"A boundary test can reveal defects that ordinary examples never expose.",evaluate:"Testing supports confidence, but the conclusion should match the coverage actually performed."},
  {id:"model-review",topic:"D1-D3",title:"Challenge: diagnose a flawed database design",skill:"analysis",
    lines:["A strong review links a design weakness to a concrete consequence.","Use the ERD, dictionary, normalisation and test evidence together.","Prioritise defects that threaten integrity, required functionality or reliable information."],
    example:"A booking table stores CustomerName but no CustomerID. Explain how duplicate names could attach bookings to the wrong person, then propose a key-based relationship.",
    help:"Use: weakness → evidence → consequence → justified correction.",
    question:"Which review statement is analytical?",answers:["Using names instead of CustomerID can mis-link duplicate names, so add a foreign-key relationship","The table has five columns","I do not like the font"],feedback:"Analysis explains how a specific design choice affects reliability and proposes a reasoned correction.",
    pairs:[["Evidence","A recorded design or test observation"],["Analysis","Explains the consequence of that evidence"]],
    analyse:"Combine structural evidence and test results instead of discussing each artefact in isolation.",evaluate:"Rank improvements by impact on requirements and integrity, not by which change is easiest to describe."},
  {id:"supported-evaluation",topic:"D1-D3",title:"Stretch: reach a supported database judgement",skill:"evaluation",
    lines:["Evaluation weighs evidence against requirements.","A useful judgement names strengths, limitations and priority improvements.","Do not claim the whole solution is successful from one passing test."],
    example:"The booking search met the speed target in the recorded test, but mobile staff still struggled with the form, so usability remains a priority even though performance is acceptable.",
    help:"Use a requirement and evidence for every important judgement, then state a limitation.",
    question:"Which conclusion is best supported?",answers:["The tested search met its target, but the form still needs usability improvement","The database is perfect because one query worked","The database is poor because the colours are boring"],feedback:"A balanced conclusion distinguishes proven strengths from remaining evidence-based weaknesses.",
    pairs:[["Strength","A requirement supported by evidence"],["Limitation","A remaining weakness or boundary of the evidence"]],
    analyse:"Different evidence can point to different strengths and weaknesses in the same solution.",evaluate:"Prioritise the next improvement by user impact, integrity risk and the client requirements."},
];
