import {makeStudyPack} from "./mini-study-pack";

export const databaseStudy=makeStudyPack("2",[
 {id:"records",topic:"A1",title:"Keep one kind of thing together",skill:"structure",
 lines:["A table stores records about one kind of thing.","A field holds one attribute, such as a book's title.","A record contains the field values for one instance."],
 example:"A library's Books table contains one record per book copy. Title and CopyID are fields; two copies of the same title still need separate records.",help:"Think: table of copies → one copy's record → its individual fields.",question:"What is a field in this library example?",answers:["The Title attribute","Every book record together","The whole library building"],feedback:"Title is an attribute represented by a field. A record holds the values for one book copy.",pairs:[["Field","One attribute of an entity"],["Record","A set of values for one instance"]],analyse:"Separating book copies lets the library track which particular copy is available.",evaluate:"Judge the structure against lending requirements, not just whether the table looks tidy."},
 {id:"keys",topic:"A1",title:"Identify a record reliably",skill:"keys",
 lines:["A primary key uniquely identifies a record and cannot be null.","A foreign key links a record to a referenced key in another table.","A person's name alone is usually unsuitable as a unique identifier."],
 example:"Two fictional library members are called Sam Lee. Separate MemberID values distinguish them, and each Loan stores the MemberID of the borrower.",help:"An identifier distinguishes records even when their descriptive details match.",question:"What should a Loan use to identify its borrower?",answers:["The borrower's unique MemberID","Only the borrower's first name","The colour of the library sign"],feedback:"A referenced MemberID distinguishes borrowers with the same name. Referential integrity checks that the referenced record exists.",pairs:[["Primary key","Uniquely identifies a record"],["Foreign key","References a key in another table"]],analyse:"Using names alone could attach a loan to the wrong person when names are shared.",evaluate:"Check uniqueness and referential integrity with test data, including attempted references to missing members."},
 {id:"relationships",topic:"A1",title:"One member, several loans",skill:"relationships",
 lines:["A one-to-many relationship connects one parent record to several child records.","Each child in this relationship refers to one parent.","Define the relationship from the organisation's rules."],
 example:"A library member can have several loans, but each loan belongs to one member. MemberID is recorded in Loans instead of adding Loan1, Loan2 and Loan3 columns to Members.",help:"Ask how many loans one member can have, then how many members one loan belongs to.",question:"Which relationship fits these stated rules?",answers:["One member to many loans","Every loan must belong to every member","Each member can have only one loan forever"],feedback:"The rules allow several loans for one member. A related Loans table handles this without a fixed set of repeated loan columns.",pairs:[["Parent record","The referenced member in this example"],["Child record","A loan referring to that member"]],analyse:"Separate loan records allow more loans without repeatedly changing the Members table's structure.",evaluate:"Confirm the actual lending rules before judging the model suitable; a different organisation may need different relationships."},
 {id:"validation",topic:"B2",title:"Valid is not always accurate",skill:"validation",
 lines:["Validation checks whether data follows an allowed rule.","Verification checks entered data against its source.","A value can pass validation and still be incorrect."],
 example:"A quantity field accepts whole numbers from 1 to 10. Entering 4 passes that rule, but the paper request may actually say 3.",help:"Allowed by the rule and matching the source are different checks.",question:"What would detect the valid but mistyped quantity?",answers:["Compare the entry with the original request","Assume a passed range check proves accuracy","Make the field a brighter colour"],feedback:"Checking against the source can reveal a plausible typing error. Validation alone cannot prove that an accepted value is true.",pairs:[["Validation","Checking whether data follows a rule"],["Verification","Checking entered data against its source"]],analyse:"Combining these checks can catch both impossible values and some plausible typing errors.",evaluate:"Test normal, boundary and invalid values, but do not claim all data is accurate merely because the rules work."},
]);

export const programmingStudy=makeStudyPack("4",[
 {id:"decompose",topic:"A1",title:"Break the problem into parts",skill:"decomposition",
 lines:["Decomposition divides a problem into smaller manageable parts.","Each part should have a clear responsibility.","The parts must still work together to solve the original problem."],
 example:"A quiz program separates showing a question, checking an answer and updating the score. Testing the answer checker alone is easier than investigating the whole quiz at once.",help:"Name what each part receives, what it does and what it returns.",question:"Which example uses decomposition?",answers:["Separate question display, answer checking and scoring","Put every unrelated task into one unnamed block","Change only the program's background colour"],feedback:"Clear responsibilities make a large problem more manageable. Integration still needs testing.",pairs:[["Decomposition","Splitting a problem into manageable parts"],["Integration","Making the parts work together"]],analyse:"An isolated answer checker can be tested with known inputs, making faults easier to locate.",evaluate:"Prefer useful boundaries, but avoid dividing simple work into so many parts that the structure becomes harder to follow."},
 {id:"variables",topic:"A1",title:"A value can change",skill:"variables",
 lines:["A variable stores a value that can change during a program.","A constant represents a value intended to remain fixed.","Choose names that describe the value's purpose."],
 example:"A quiz updates score after each correct answer. Its configured maximum number of questions remains fixed for that quiz run.",help:"Ask which value changes as the task runs and which is intended to stay the same.",question:"Which value should change after a correct quiz answer?",answers:["The current score","The meaning of the word quiz","The fixed maximum number of questions"],feedback:"The score changes as answers are marked. A meaningful name helps explain that changing state.",pairs:[["Variable","A stored value that can change"],["Constant","A value intended to remain fixed"]],analyse:"A descriptive score variable makes later calculations easier to understand than an unexplained single-letter name.",evaluate:"Readable names help maintenance, but test the update logic too; good names do not establish correctness."},
 {id:"selection",topic:"A4–A6",title:"Choose a path using a condition",skill:"selection",
 lines:["Selection chooses which instructions run based on a condition.","A condition has a true or false result.","Check what happens on both sides of a boundary."],
 example:"A practice quiz gives a success message when score is at least 3. Scores of 2 and 3 test the two sides of that decision boundary.",help:"At least 3 includes 3; more than 3 does not.",question:"For score at least 3, which score just meets the condition?",answers:["3","2","0"],feedback:"At least 3 means 3 or more. Testing 2 and 3 can expose an incorrect comparison operator.",pairs:[["Selection","Choosing instructions using a condition"],["Boundary test","Checking values at the edge of a rule"]],analyse:"Using more than instead of at least would wrongly reject a score exactly at the threshold.",evaluate:"Use expected outcomes to test both branches before judging the decision correct."},
 {id:"iteration",topic:"A4–A6",title:"Repeat with a stopping rule",skill:"iteration",
 lines:["Iteration repeats a set of instructions.","A loop needs a suitable stopping condition or limit.","Trace how the values change during each repetition."],
 example:"A quiz shows each of four questions once. A counter increases after each question so the loop can stop after question four.",help:"Write the counter value before and after each repetition.",question:"What could stop this count-controlled loop ending as intended?",answers:["The counter never increases towards its stopping limit","Each question has a clear title","The program uses readable names"],feedback:"If the counter cannot reach the stopping condition, repetition may continue unexpectedly. Trace the update and condition together.",pairs:[["Iteration","Repeating instructions"],["Trace","Following changing values step by step"]],analyse:"A missing counter update can trap the user in repeated questions rather than completing the quiz.",evaluate:"Test zero, one and several repetitions where the design permits them, and verify that the final question is not skipped or repeated."},
]);

export const iotStudy=makeStudyPack("19",[
 {id:"sense-act",topic:"A2",title:"Sensing is different from acting",skill:"components",
 lines:["A sensor measures a physical condition.","A controller processes information and applies a decision rule.","An actuator changes something in the physical environment."],
 example:"In a fictional greenhouse, a temperature sensor reports a reading. A controller decides whether to open a vent, and a motor moves it.",help:"Follow measure → decide → act.",question:"Which component physically opens the vent?",answers:["The motor actuator","The stored temperature number","The label printed on the sensor"],feedback:"The motor acts on the environment. The sensor measures, and the controller decides what response is needed.",pairs:[["Sensor","Measures a physical condition"],["Actuator","Produces a physical change"]],analyse:"Separating these roles helps locate whether a fault comes from measurement, the decision or the physical response.",evaluate:"Check the whole chain; a correct sensor reading alone does not prove the vent will open safely."},
 {id:"edge-cloud",topic:"B2",title:"Where should a decision happen?",skill:"processing",
 lines:["Edge processing happens near the source of the data.","Cloud processing uses remote computing services.","Choose where work happens using response, connection and resource needs."],
 example:"The greenhouse controller can open a vent locally when it gets too warm, while a remote service stores trends. A lost internet connection need not stop that designed local rule.",help:"Ask which actions must still work without the remote service.",question:"Which task best supports a response during an internet outage?",answers:["Run the required vent-control rule on the local controller","Require every decision to wait for a remote server","Assume the internet can never fail"],feedback:"A locally implemented rule can operate without that remote round trip. The design still needs power, sensor and failure handling.",pairs:[["Edge processing","Processing near the data source"],["Cloud processing","Processing using remote computing services"]],analyse:"Local control can reduce dependence on a remote connection for the immediate response.",evaluate:"Balance this benefit against local maintenance and hardware limits; neither location is best for every task."},
 {id:"communication",topic:"B4-B5",title:"Choose a link for the task",skill:"communication",
 lines:["Range is the distance a connection can cover under given conditions.","Latency is the delay before information reaches its destination.","Power use and reliability also affect communication choices."],
 example:"A battery-powered greenhouse sensor sends a small reading every minute. A live video camera has very different data and power needs, even in the same building.",help:"Start with the amount of data, required delay, distance and available power.",question:"What should guide the sensor's communication choice?",answers:["Its range, power, data and response requirements","Only the most impressive product name","Always copying the video camera's configuration"],feedback:"Communication needs depend on the task and environment. A suitable choice for video may be unsuitable for a low-power sensor.",pairs:[["Range","Distance a connection can cover in given conditions"],["Latency","Delay in delivering information"]],analyse:"A power-hungry link may shorten battery life and increase maintenance visits.",evaluate:"Test in the intended location, including obstacles, before accepting a claimed range as evidence of reliable operation."},
 {id:"failure",topic:"C3",title:"Test missing and implausible readings",skill:"testing",
 lines:["A plausible-looking reading can still be wrong.","Missing, stale and out-of-range readings need defined handling.","Test failures as well as normal operation."],
 example:"The greenhouse screen still shows yesterday's temperature after a sensor disconnects. Displaying when the reading was received helps staff recognise that it may no longer be current.",help:"Check the value, its time and whether communication is still working.",question:"What makes the disconnected sensor's display less misleading?",answers:["Show the reading time and a clear stale-data warning","Present yesterday's value as a fresh measurement","Hide every connection failure from staff"],feedback:"A timestamp and warning communicate the limitation. The control system also needs a defined response appropriate to its risks.",pairs:[["Stale data","Information too old for its intended use"],["Failure test","Checking behaviour when something goes wrong"]],analyse:"An old value presented as current can lead staff to make an unsuitable decision about ventilation.",evaluate:"Judge reliability using normal and failure tests, with safe fallback behaviour suited to the intended environment."},
]);
