import {makeStudyPack,type ShortStudyIdea} from "./mini-study-pack";

/**
 * Small reinforcement lessons that mirror the tutor's confirmed classroom
 * progress. They are deliberately practical and cumulative: learners first
 * recognise one construct, then combine it with earlier constructs in the same
 * way they have done in class. Hima remains second practice, not first teaching.
 */
const unit4TaughtIdeas:ShortStudyIdea[]=[
  {id:"program-environment",topic:"A4",title:"Read the shape of a Python program",skill:"program-flow",
    lines:["A Python program normally starts by importing what it needs and setting up values or functions before the main running section.","Functions are defined before they are called, while the main program decides when to call them.","In a game, setup happens once but the game loop repeats while the game is running."],
    example:"A runner game can import pygame, define jump(), set running = True, then enter while running: to keep checking input and updating the screen.",
    help:"Read the file from top to bottom and label each part: setup, function definitions, main loop and shutdown.",
    question:"Which part normally repeats continuously while a Pygame game is running?",answers:["The main while loop","The import statements","The function definition line"],
    feedback:"The main while loop repeatedly processes events, updates values and redraws the game. Imports and function definitions are normally set up before that loop.",
    pairs:[["Setup","Runs once before the main loop"],["Main loop","Repeats while the program is running"]],
    analyse:"Separating setup from the repeating section makes it easier to see which values should be created once and which behaviour must happen every frame.",
    evaluate:"A clear program structure is easier to test and change because repeated behaviour is not mixed with one-time setup."},

  {id:"indentation",topic:"A4",title:"Python indentation and code blocks",skill:"indentation",
    lines:["Python uses indentation as part of its syntax, not just to make code look tidy.","Indented lines belong to the function, loop or if block above them.","A colon normally starts a new block after def, if, elif, else, for or while."],
    example:"def greet(name):\n    print(\"Hello\", name)\n\ngreet(\"Sam\")",
    help:"After a line ending with a colon, look for the indented block underneath it. Keep the same indentation level for lines that belong together.",
    question:"Why is the print line indented under def greet(name):?",answers:["Because it belongs inside the function","Because print always needs four spaces everywhere","Because indentation is optional in Python"],
    feedback:"Python uses indentation to define the function body. Incorrect indentation can change the program structure or cause an error.",
    pairs:[["Colon :","Starts a code block"],["Indentation","Shows which statements belong inside that block"]],
    analyse:"Correct indentation makes control flow visible and is required for Python to understand where a block begins and ends.",
    evaluate:"Use consistent indentation throughout a program; four spaces is the usual Python convention.",
    codePractice:{prompt:"Type a correct function called greet with one parameter called name. Inside it, print Hello followed by the name. Then call greet with Sam. Indentation must be correct.",starter:"def greet(name):\nprint(\"Hello\", name)\n\ngreet(\"Sam\")",answer:"def greet(name):\n    print(\"Hello\", name)\n\ngreet(\"Sam\")",feedback:"The print statement belongs inside the function, so it must be indented. The function call is outside the function and returns to the left margin."}},

  {id:"functions-basics",topic:"A4",title:"Function 1: define it, then call it",skill:"functions",
    lines:["A function groups instructions under a reusable name.","Writing def creates the function; writing the function name with brackets calls it.","The code inside the function only runs when the function is called."],
    example:"def jump(): groups the instructions for a Pony Runner jump. Writing jump() later calls that function.",
    help:"Look for the function name after def, then find where the same name is followed by brackets to run it.",
    question:"Which line calls a function that was defined as def jump():?",answers:["jump()","def jump():","while jump:"],
    feedback:"The definition starts with def. Writing jump() calls the function and runs its instructions.",
    pairs:[["def jump():","Defines the function"],["jump()","Calls the function"]],
    analyse:"Putting repeated jump behaviour in one function reduces duplicated instructions in the game.",
    evaluate:"A function should have one clear job so it remains easy to test and change."},

  {id:"function-two",topic:"A4",title:"Function 2: pass a value into a function",skill:"parameters",
    lines:["A parameter is a named value a function receives when it is called.","The same function can therefore work with different values instead of repeating almost identical code.","The argument is the actual value supplied in the function call."],
    example:"def move(speed): can use speed inside the function. Calling move(5) and move(9) uses the same instructions with different values.",
    help:"Read the name inside the brackets in def first, then match it to the value placed inside the brackets when the function is called.",
    question:"In move(8), what is 8?",answers:["The argument passed into the function","The function name","A while-loop condition"],
    feedback:"The parameter is named in the function definition. The argument is the value supplied when the function is called.",
    pairs:[["Parameter","Name used by the function to receive a value"],["Argument","Actual value supplied in a call"]],
    analyse:"Parameters make movement code reusable because speed can change without creating another move function.",
    evaluate:"Use parameters for values the caller genuinely needs to vary; too many unrelated parameters can make a function difficult to understand.",
    codePractice:{prompt:"Write a function called add_points with parameters score and bonus. Return score + bonus. Then print the result of add_points(10, 5).",starter:"def add_points(score, bonus):\n    # write the return line\n\n# call the function and print the result",answer:"def add_points(score, bonus):\n    return score + bonus\n\nprint(add_points(10, 5))",feedback:"The parameters belong inside the brackets, the return line is indented inside the function, and the function call supplies the arguments 10 and 5."}},

  {id:"while-practice",topic:"A4-A6",title:"While loop: keep going until the condition changes",skill:"iteration",
    lines:["A while loop repeats while its condition is True.","Something inside or around the loop must eventually change the condition when the program needs to stop.","Game loops often use a Boolean variable such as running."],
    example:"running = True followed by while running: keeps the game active until an event changes running to False.",
    help:"Ask two questions: what condition keeps the loop running, and what can change that condition?",
    question:"What must happen for while running: to stop when running started as True?",answers:["running must become False","running must stay True forever","The function name must change"],
    feedback:"The loop continues while its condition is True. Changing running to False lets the program leave the loop.",
    pairs:[["while running:","Repeats while running is True"],["running = False","Allows the loop to finish"]],
    analyse:"A Boolean running flag gives the program one clear state controlling whether the repeated game loop continues.",
    evaluate:"Always check that a while loop has a realistic stopping route so it cannot continue accidentally forever.",
    codePractice:{prompt:"Write a while loop that starts count at 1, prints count while it is less than or equal to 3, and increases count by 1 each time.",starter:"count = 1\nwhile count <= 3:\n    # print and update count",answer:"count = 1\nwhile count <= 3:\n    print(count)\n    count = count + 1",feedback:"Both statements are indented inside the while loop. Updating count is essential so the condition eventually becomes False."}},

  {id:"return-values-practice",topic:"A4",title:"Return: send a result back from a function",skill:"return-values",
    lines:["A function can calculate a result and return it to the code that called the function.","return ends that function call and provides a value that can be stored or used.","Printing a value displays it; returning a value lets the rest of the program use it."],
    example:"def next_x(x, speed): return x + speed lets the main program write player_x = next_x(player_x, speed).",
    help:"Look for what the function produces, then look for where the returned value is stored after the call.",
    question:"Why return x + speed instead of only printing it?",answers:["So the caller can store and use the new position","So the while loop is deleted","So the function can never be called again"],
    feedback:"A returned value can be assigned to a variable and used elsewhere in the program.",
    pairs:[["print(value)","Displays a value"],["return value","Sends a value back to the caller"]],
    analyse:"Returning the new position keeps the calculation inside the function while allowing the main game loop to own the player's current state.",
    evaluate:"Return useful results rather than relying on unnecessary global variables when the caller needs the value."},

  {id:"function-while",topic:"A4-A6",title:"Combine a function with a while loop",skill:"function-loop",
    lines:["A while loop controls repetition and a function performs a focused job inside that repetition.","The loop can call the same function many times as values change.","This is common in games where movement or drawing happens every frame."],
    example:"while running: player_x = move_player(player_x, speed) repeatedly calls the same movement function while the game stays active.",
    help:"Separate the jobs: the while loop decides whether to repeat; the function decides what one repeated action does.",
    question:"In while running: player_x = move_player(player_x, speed), what controls repetition?",answers:["The while loop","The parameter named speed","The return keyword by itself"],
    feedback:"The while loop controls whether another cycle runs. The function carries out one piece of work during that cycle.",
    pairs:[["while loop","Controls repeated cycles"],["Function call","Performs one focused job during a cycle"]],
    analyse:"Combining a loop with a small function keeps repeated code shorter and makes the movement calculation easier to test separately.",
    evaluate:"Keep the loop readable by moving substantial repeated jobs into clearly named functions instead of putting everything in one long block."},

  {id:"function-while-if",topic:"A4-A6",title:"Combine a function, while loop and if decision",skill:"combined-control",
    lines:["A while loop repeats the game cycle, an if statement chooses what should happen, and a function performs the selected action.","The if condition should be checked each cycle when the decision depends on changing game state.","This lets a repeated loop react differently to different situations."],
    example:"while running: if jumping: player_y = update_jump(player_y) combines repetition, a decision and a reusable function.",
    help:"Label the three jobs: while = repeat, if = decide, function = do the action.",
    question:"Which construct decides whether update_jump() is called?",answers:["The if statement","The import statement","The function definition alone"],
    feedback:"The if condition chooses whether the function call happens during that loop cycle.",
    pairs:[["while","Repeat"],["if","Decide"]],
    analyse:"The combination lets the game keep running while only applying jump behaviour when the jumping state is active.",
    evaluate:"Use clear Boolean state names such as jumping or game_over so the decision logic remains understandable."},

  {id:"choice-menu-if",topic:"A4-A6",title:"Build a simple menu using choice and if",skill:"menu-selection",
    lines:["A menu displays options and stores the user's choice.","An if or elif chain compares that choice with the available options.","Each valid option should trigger a clear action and unexpected input should be handled deliberately."],
    example:"choice = input('1 Play, 2 Help: ') followed by if choice == '1': starts the game, while elif choice == '2': shows help.",
    help:"Trace one possible choice at a time and mark which branch should run.",
    question:"If choice contains '2', which branch should run?",answers:["The branch checking choice == '2'","Every branch at the same time","The while condition automatically"],
    feedback:"Selection checks the stored choice and runs the matching branch.",
    pairs:[["choice","Stores the selected menu option"],["if / elif","Chooses the matching action"]],
    analyse:"A menu turns one stored input value into different program paths without needing separate programs.",
    evaluate:"Give users clear options and handle invalid entries rather than assuming every input will be correct."},

  {id:"function-menu-choice-if",topic:"A4-A6",title:"Put the menu inside a function",skill:"modular-menu",
    lines:["A menu can be placed in its own function so the main program does not contain all of the display and choice logic.","The function can return the chosen option to the caller.","The main program can then use if statements to decide what to run next."],
    example:"def show_menu(): ... return choice followed by choice = show_menu() and if choice == '1': play_game().",
    help:"Follow the data: show_menu gets the input, return sends it back, choice stores it, and if selects the next action.",
    question:"What should show_menu() return if the main program needs to decide what happens next?",answers:["The user's choice","The text def","The while keyword"],
    feedback:"Returning the user's choice lets the main program make the next decision without relying on hidden global state.",
    pairs:[["show_menu()","Collects and returns a menu choice"],["if choice == ...","Uses that returned choice"]],
    analyse:"Separating menu input from game actions gives each function a clearer responsibility and makes the program easier to extend.",
    evaluate:"A menu function should not secretly perform unrelated game logic if returning the choice keeps responsibilities clearer."},

  {id:"lists-practical",topic:"A4",title:"Use a list, display values and change a value",skill:"lists",
    lines:["A list stores several values in one ordered collection.","Each item can be read using its index and a mutable list item can be changed by assigning a new value at that index.","A loop can display every value without writing a separate print statement for each item."],
    example:"scores = [10, 20, 30]; scores[1] = 25 changes the second value, and for score in scores: print(score) displays the list values.",
    help:"Remember that Python list indexes start at 0, so index 1 refers to the second item.",
    question:"What does scores[1] = 25 change in [10, 20, 30]?",answers:["The second value, making the list [10, 25, 30]","The first value","The length of the list only"],
    feedback:"Python indexes begin at 0. Index 1 is therefore the second item.",
    pairs:[["Index","Position used to access a list item"],["Assignment to list[index]","Changes that stored item"]],
    analyse:"Lists avoid separate variables such as obstacle1, obstacle2 and obstacle3 when the program needs to process similar items together.",
    evaluate:"Use a list when the values belong in an ordered collection and the program benefits from processing them consistently."},

  {id:"pandas-practical",topic:"A4",title:"Pandas: display and change table values",skill:"pandas",
    lines:["Pandas works with labelled table-like data using a DataFrame.","A DataFrame can display rows and columns and let code select or change values deliberately.","The labels make structured data easier to work with than a collection of unrelated variables."],
    example:"A DataFrame with Name and Score columns can be displayed, then a selected Score value can be changed before the updated table is shown again.",
    help:"Think row + column = one specific value. Identify both before changing data.",
    question:"What does a DataFrame mainly represent in this lesson?",answers:["Table-like data with rows and columns","A Pygame collision box","A while-loop condition"],
    feedback:"A DataFrame stores structured tabular data in labelled rows and columns.",
    pairs:[["Row","One record in the table"],["Column","One named field across records"]],
    analyse:"Using labelled columns can make it clearer which value is being read or changed compared with relying only on numeric positions.",
    evaluate:"Pandas is useful for structured data work, but it should be used because the data task needs it rather than added to a game unnecessarily.",
    codePractice:{prompt:"Using pandas as pd, create a DataFrame from the data dictionary below and print the DataFrame. Data: Name = Aisha, Ben; Score = 10, 12.",starter:"import pandas as pd\n\ndata = {\"Name\": [\"Aisha\", \"Ben\"], \"Score\": [10, 12]}\n# create df\n# print df",answer:"import pandas as pd\n\ndata = {\"Name\": [\"Aisha\", \"Ben\"], \"Score\": [10, 12]}\ndf = pd.DataFrame(data)\nprint(df)",feedback:"pd.DataFrame(data) turns the dictionary into a DataFrame, and print(df) displays the table."}},

  {id:"pygame-runner-loop",topic:"A4-A6",title:"Pygame runner: understand the main game loop",skill:"pygame-loop",
    lines:["A Pygame runner game repeatedly checks events, updates game values and redraws the scene.","The main while loop keeps these steps happening many times per second.","Functions can separate jobs such as moving the player, drawing the background and creating obstacles."],
    example:"while running: can process events, call update_player(), call update_obstacles(), draw the scene and then update the display.",
    help:"Read one frame as input → update → draw. Then remember the while loop starts the next frame.",
    question:"Which order best describes one simple game-loop cycle?",answers:["Check input, update values, draw the frame","Define every function again, then import pygame again","Close the window before checking input"],
    feedback:"A game loop repeatedly handles input/events, updates state and renders the next frame.",
    pairs:[["Update","Change positions or game state"],["Draw","Render the current state on screen"]],
    analyse:"Keeping update and draw stages clear helps diagnose whether a problem is caused by wrong values or by how the screen is rendered.",
    evaluate:"The exact architecture can vary, but the loop should remain understandable enough to test individual behaviours."},

  {id:"pygame-moving-world",topic:"A4-A6",title:"Move the character and scrolling background",skill:"pygame-movement",
    lines:["Movement changes position values over time rather than teleporting a sprite once.","A scrolling background can move its x position every frame and wrap or reset when it reaches a boundary.","The same while loop can update both the character and the background using separate functions."],
    example:"update_player() can change player_x or player_y while update_background() decreases background_x so the world appears to move.",
    help:"Track the x or y value across three frames and check whether it changes in the expected direction.",
    question:"What creates the appearance of a continuously scrolling background?",answers:["Changing its position repeatedly inside the game loop","Drawing it once before the loop and never changing it","Only renaming the background variable"],
    feedback:"Repeated position updates across frames create visible movement.",
    pairs:[["Player position","Controls where the character is drawn"],["Background position","Controls where the scrolling scene is drawn"]],
    analyse:"Separating player and background updates allows the character to jump while the world continues scrolling independently.",
    evaluate:"Movement speed should be controlled consistently so the game remains playable and does not depend unpredictably on computer speed."},

  {id:"pygame-obstacles",topic:"A4-A6",title:"Add colourful obstacles using functions, loops and if",skill:"pygame-obstacles",
    lines:["Obstacles can be stored as values or objects and updated repeatedly inside the main loop.","A function can create or move obstacles, while an if statement decides what happens when an obstacle reaches a boundary or collides with the player.","A loop lets the same logic process several obstacles instead of writing separate code for each one."],
    example:"for obstacle in obstacles: move_obstacle(obstacle); if obstacle.colliderect(player): game_over = True combines a collection, loop, function call and decision.",
    help:"Trace one obstacle first: create → move → test collision → reset or end. Then apply the same logic to the whole list.",
    question:"Why put obstacles in a list and loop through them?",answers:["The same movement and collision logic can process several obstacles","It means collision checks are no longer needed","Every obstacle must have exactly the same position"],
    feedback:"A collection and loop let one reusable set of instructions process multiple obstacles.",
    pairs:[["Obstacle list","Stores several obstacles"],["Collision if statement","Chooses what happens when player and obstacle meet"]],
    analyse:"This structure combines the core ideas already learned: variables hold positions, a loop repeats, functions organise behaviour and if statements react to conditions.",
    evaluate:"A working runner game should still be checked for readable structure, sensible function responsibilities and predictable collision behaviour."},
];

  {id:"requirements-analysis",topic:"B1",title:"Turn a problem into clear requirements",skill:"requirements",
    lines:["Requirements describe what the software must do and the constraints it must work within.","Functional requirements describe behaviours or features; non-functional requirements describe qualities such as usability, performance or reliability.","A programmer should understand the problem before jumping into code."],
    example:"For a runner game, a functional requirement could be 'the player can jump over obstacles'. A non-functional requirement could be 'the controls should respond quickly enough to feel playable'.",
    help:"Ask: who is the user, what do they need to do, what data is involved, and what rules or limits matter?",
    question:"Which is a functional requirement?",answers:["The player must be able to jump over an obstacle","The program should be easy to maintain","The interface should look professional"],
    feedback:"A functional requirement describes what the system must do. Maintainability and appearance are quality-related non-functional requirements.",
    pairs:[["Functional requirement","What the system must do"],["Non-functional requirement","A quality or constraint the system should meet"]],
    analyse:"Clear requirements give programmers something specific to design, code and test against instead of relying on assumptions.",
    evaluate:"Good requirements should be clear, testable and linked to the user's actual need rather than vague statements such as 'make it good'."},

  {id:"testing-evidence",topic:"C1-C2",title:"Testing and evidence: prove that the program works",skill:"testing-evidence",
    lines:["Testing compares actual behaviour with an expected result.","A useful test records the input, expected result, actual result and whether the test passed.","Evidence can include screenshots, output, test tables and explanations that show what was checked.","Typical, boundary/extreme and erroneous data help test different kinds of behaviour."],
    example:"For an age rule allowing 16 to 99, test 25 as typical, 16 and 99 as boundary values, and 15 or text as erroneous input. Record expected and actual results.",
    help:"Do not write 'it works'. Show what you tested, what you expected and what actually happened.",
    question:"Which is the strongest testing evidence?",answers:["Input 16, expected accepted, actual accepted, pass","It worked when I tried it","The code looks correct"],
    feedback:"Strong evidence records the exact test and outcome so another person can understand what was checked.",
    pairs:[["Expected result","What should happen before the test is run"],["Actual result","What really happened when the test was run"]],
    analyse:"Recording expected and actual outcomes makes bugs easier to locate and provides evidence that requirements have been checked.",
    evaluate:"Passing a few tests does not prove a program has no bugs; test cases should cover important paths, boundaries and invalid input."},

const unit6TaughtIdeas:ShortStudyIdea[]=[
  {id:"html-page-basics",topic:"B2",title:"Build the basic structure of an HTML page",skill:"html",
    lines:["An HTML page uses html, head and body to organise the document.","The title belongs in the head and visible page content belongs in the body.","Headings, paragraphs, div, section and main organise visible content."],
    example:"A page can place its title in the head, then use main with an h1, paragraph and sections in the body.",
    help:"Ask whether the content describes the page to the browser or is meant to appear on the page itself.",
    question:"Where should the visible h1 and paragraph normally be placed?",answers:["Inside the body","Inside the title element","Outside the html element"],
    feedback:"Visible page content belongs in the body. The title element belongs in the head.",
    pairs:[["head","Page information such as the title"],["body","Visible page content"]],
    analyse:"A clear structure makes the page easier to extend and helps separate document information from visible content.",
    evaluate:"Use semantic elements such as main and section when they describe the content rather than adding them only for appearance."},
  {id:"links-images-folders",topic:"B2",title:"Link pages and add images using the right paths",skill:"html-links",
    lines:["The a element links one page or resource to another using href.","The img element loads an image using src and should have useful alternative text when the image conveys information.","Relative paths depend on where files and folders are stored."],
    example:"If index.html and about.html are in the same folder, href=\"about.html\" links them. An image in an images folder can use src=\"images/logo.png\".",
    help:"Start from the current HTML file and trace the folders needed to reach the target file.",
    question:"index.html and about.html are in the same folder. Which href links to the About page?",answers:["about.html","images/about.html","#about.png"],
    feedback:"Files in the same folder can be linked using the target file name as the relative path.",
    pairs:[["href","Destination used by a link"],["src","Resource path used by an image"]],
    analyse:"Keeping predictable folders and relative paths makes a multi-page website easier to move and maintain.",
    evaluate:"Test every link and image from the actual folder structure rather than assuming a path is correct."},
  {id:"css-methods",topic:"B2",title:"Choose inline, internal or external CSS",skill:"css",
    lines:["Inline CSS is written on an individual HTML element using its style attribute.","Internal CSS is written in a style element in the page head.","External CSS is stored in a separate stylesheet and linked to the HTML page.","A class selector lets the same style be applied to several elements."],
    example:"Several pages can link to styles.css so one class rule changes the same type of content across the site.",
    help:"Ask how many elements or pages need the rule. Repeated site-wide styles are usually easier to maintain in an external stylesheet.",
    question:"Which approach best shares the same styles across several HTML pages?",answers:["Link the pages to an external CSS file","Repeat every rule as inline CSS","Put a different style attribute on every element"],
    feedback:"An external stylesheet can be linked by several pages, reducing repeated presentation rules.",
    pairs:[["Internal CSS","Rules in a style element in the page head"],["External CSS","Rules in a separate linked stylesheet"]],
    analyse:"A shared stylesheet reduces duplication because the same class rule can control presentation on several pages.",
    evaluate:"Inline CSS can be useful for a very isolated case, but repeated site styling is usually easier to maintain when rules are separated and reused."},
];

export const unit4TaughtProgressStudy=makeStudyPack("4",unit4TaughtIdeas);
export const unit6TaughtProgressStudy=makeStudyPack("6",unit6TaughtIdeas);
