import type { StudyLesson, StudyQuestionKey } from "./mini-study";
import {dataModellingStudy} from "./mini-study-data-modelling";
import {securityStudy} from "./mini-study-security";
import {cloudStudy} from "./mini-study-cloud";
import {projectStudy} from "./mini-study-projects";
import {databaseStudy,programmingStudy,iotStudy} from "./mini-study-active-units";

export const studySources = {
  pearson:"https://qualifications.pearson.com/content/dam/pdf/BTEC-Nationals/Information-Technology/2016/specification-and-sample-assessments/specification-pearson-btec-level-3-national-extended-diploma-in-information-technology.pdf",
  wai:"https://www.w3.org/WAI/fundamentals/accessibility-principles/",
};

function choice(id:string, skill:string, prompt:string, answers:string[], explanation:string): StudyQuestionKey {
  return {id,skill,kind:"choice",prompt,options:answers.map((text,i)=>({id:`o${i+1}`,text})),answer:"o1",explanation};
}
function matching(id:string, skill:string, pairs:[string,string][], explanation:string): StudyQuestionKey {
  return {id,skill,kind:"match",prompt:"Match each idea to its meaning.",
    stems:pairs.map(([text],i)=>({id:`s${i+1}`,text})),options:pairs.map(([,text],i)=>({id:`o${i+1}`,text})),
    answer:Object.fromEntries(pairs.map((_,i)=>[`s${i+1}`,`o${i+1}`])),explanation};
}
type LessonInput = {id:string;title:string;skill:string;lines:string[];example:string;support:string;question:string;answers:string[];feedback:string;pairs:[string,string][];analysis:string;evaluation:string;wai?:boolean;topicCode?:string};
function lesson(input:LessonInput):StudyLesson {
  return {id:`u6-${input.id}-v1`,unitCode:"6",topicCode:input.topicCode??"A1",title:input.title,skill:input.skill,lines:input.lines,example:input.example,support:input.support,analysis:input.analysis,evaluation:input.evaluation,
    questions:[choice(`${input.id}-check`,input.skill,input.question,input.answers,input.feedback),matching(`${input.id}-pairs`,input.skill,input.pairs,input.feedback)],
    sources:[studySources.pearson,...(input.wai?[studySources.wai]:[])]};
}

/** Original short self-study resources for Unit 6 learning aim A. Not an assignment, grade or claim of WCAG certification. */
export const unit6StudyLessons: StudyLesson[] = [
  lesson({id:"purpose",title:"Who is this website for?",skill:"purpose",
    lines:["A website's audience is the people it is designed for.","Its purpose is what it helps them do.","Judge features against that task, not your favourite colour."],
    example:"For a bus website, a passenger needs to find a route and departure time. A large timetable search helps that task more than a decorative animation.",
    support:"Ask: who is using it, and what are they trying to finish?",
    question:"Which feature best supports a passenger checking their next bus?",answers:["A clear route and departure-time search","A full-screen animation with no timetable link","A list of the designer's favourite colours"],feedback:"Match the feature to the passenger's task: finding their route and departure time.",pairs:[["Audience","The people using the website"],["Purpose","The task the website helps them do"]],analysis:"Because the search is easy to find, passengers need fewer steps to reach departure times.",evaluation:"The search is useful for regular passengers, but its value still depends on accurate timetable data."}),
  lesson({id:"usability",title:"Make a task easy to finish",skill:"usability",
    lines:["Usability is how well people can complete their task.","Look for clear labels, understandable steps and helpful feedback.","Observe a task to find problems instead of guessing."],
    example:"Website A labels a button 'Find a course'. Website B labels the same action 'Explore possibilities'. Ask a new visitor to find a course on each site.",support:"A useful label tells you what will happen when you select it.",
    question:"Which observation is useful evidence about usability?",answers:["A new visitor finds the course without help","The designer says the website is perfect","The homepage uses your favourite colour"],feedback:"An observed task tells you whether a visitor can use the website. Preference alone does not prove usability.",pairs:[["Clear label","Tells the user what an action does"],["Task observation","Shows what happens when someone tries it"]],analysis:"A clear label can reduce hesitation, so a first-time visitor may reach the course more easily.",evaluation:"Prefer A for new visitors if the task evidence supports it; one visitor alone is limited evidence."}),
  lesson({id:"accessibility",title:"Access for different users",skill:"accessibility",wai:true,
    lines:["Accessibility includes people with disabilities.","W3C publishes WCAG guidance for web content.","A site can look attractive and still contain barriers."],
    example:"A learner who cannot use a mouse needs to reach and activate the course link with a keyboard.",support:"Think about a person using the same page in a different way.",
    question:"What is the most useful check for someone who cannot use a mouse?",answers:["Try reaching and activating the link with a keyboard","Check only whether the logo is colourful","Count the images on the homepage"],feedback:"Keyboard access helps users who cannot use a mouse. This one check alone does not establish full WCAG conformance.",pairs:[["W3C","Publishes web standards and guidance"],["WCAG","Guidelines for accessible web content"]],analysis:"A keyboard barrier can prevent a learner from reaching course information at all.",evaluation:"A site with keyboard access is better for this task, but other accessibility requirements still need checking."}),
  lesson({id:"evidence",title:"Compare the same task",skill:"evidence",
    lines:["A fair comparison uses the same task on both websites.","Record what you observed and how you checked it.","Separate a fact from your opinion about it."],
    example:"On both college websites, find entry requirements for the same type of course. Record the route taken and any confusing labels.",support:"Use the same device and task where possible. Say what you could not check.",
    question:"Which comparison gives the most useful evidence?",answers:["Try the same course-search task on both sites and record the steps","Compare a shop checkout with a college contact page","Decide from the logos without trying either site"],feedback:"Using the same task makes the observations more comparable. Explain differences in device, content or users that limit the comparison.",pairs:[["Observation","What you actually saw or tested"],["Opinion","What you think about the result"]],analysis:"B needs an extra menu step, which may make the entry requirements harder to find.",evaluation:"A was easier in this test, but that does not prove every task is easier on A."}),
  lesson({id:"analysis",title:"Explain the effect",skill:"analysis",
    lines:["Analysis connects a feature to its effect on a user.","Use: feature → effect → why it matters for the task.","Compare the effect on both websites using your observations."],
    example:"A uses 'Entry requirements'; B uses 'Further details'. A's specific label may reduce guessing, helping applicants decide whether they can apply.",support:"Try this sentence: Because the site has…, the user can…, which helps them to…",
    question:"Which sentence analyses rather than just describes?",answers:["The specific label reduces guessing, helping applicants find the requirements","The website has a blue button","The page contains three pictures"],feedback:"Analysis develops a consequence for the audience and purpose. Naming colours or counting features only describes them.",pairs:[["Describe","Say what is there"],["Analyse","Explain the linked effects and why they matter"]],analysis:"Use a because/therefore link, but support it with a real observation.",evaluation:"Consider whether the same feature might help one audience but confuse another."}),
  lesson({id:"evaluation",title:"Reach a supported judgement",skill:"evaluation",
    lines:["Evaluation weighs the evidence before making a judgement.","Say which website is better for this audience and task, and why.","Include an important limitation or trade-off."],
    example:"A was easier for finding entry requirements in our test. However, we tested only one course on a laptop, so we cannot conclude that A is better on every device.",support:"Try: I judge A more suitable for… because… However, my evidence is limited by…",
    question:"Which is the strongest supported judgement?",answers:["A was easier for this tested task, but we have not checked mobile use","A is always best because I like it","Both sites have menus, so there is nothing to judge"],feedback:"A judgement needs evidence, context and a limitation. These skills support evaluative writing; a practice answer does not award a qualification grade.",pairs:[["Judgement","A conclusion supported by evidence"],["Limitation","A reason the conclusion may not apply everywhere"]],analysis:"Explain which evidence matters most for the audience rather than listing every feature.",evaluation:"Name a realistic improvement and explain why it would address the most important weakness."}),
];

// Further short ideas cover visual design and performance without adding a
// second task to the learner's day. Stable IDs retain all completed evidence.
unit6StudyLessons.push(
 lesson({id:"visual-hierarchy",title:"Make the important thing stand out",skill:"usability",
  lines:["Visual hierarchy uses size, position and contrast to suggest importance.","Proportion describes the sizes of elements in relation to each other.","The golden ratio, about 1:1.618, is one design reference—not proof of usability."],
  example:"A college page gives a decorative photograph most of the space and makes its Apply button tiny. Attractive proportions do not help applicants if the main action is difficult to find.",support:"Look first at what catches your eye. Is it what the intended user needs?",
  question:"What best tests whether this creative layout works for applicants?",answers:["Observe whether applicants can find and use the Apply button","Check only that the layout uses the golden ratio","Assume the biggest photograph makes every task easier"],feedback:"A design reference can guide composition, but observed task performance is needed to judge usability for the audience.",pairs:[["Visual hierarchy","Using visual differences to suggest importance"],["Proportion","Sizes of elements in relation to each other"]],analysis:"A small low-emphasis Apply button can be overlooked, delaying the task even when the photograph is attractive.",evaluation:"Keep creative features that support the purpose, but prioritise a discoverable main action and retest with applicants."}),
 lesson({id:"search-discovery",title:"Help people find the right page",skill:"discovery",
  lines:["Search engines can discover pages by crawling links and store information in an index.","Search engine optimisation helps make relevant content discoverable and understandable.","Accurate titles, useful wording and maintained content help; no keyword guarantees first place."],
  example:"A college names a page 'Level 3 IT course: entry requirements' and keeps its course details current. Calling it 'Page 7' gives people and search services much less useful context.",support:"Use the words the audience needs, honestly describing what is on the page.",
  question:"Which change best helps someone identify the relevant course page?",answers:["Give it an accurate descriptive title and maintain its information","Repeat unrelated popular words throughout the page","Promise a first-place search result from one keyword"],feedback:"Relevant titles and maintained content support discovery and understanding. Search placement is not guaranteed, and misleading keywords do not serve the visitor's task.",pairs:[["Crawling","Discovering pages by following links"],["Indexing","Storing information about discovered content"]],analysis:"A descriptive course title can help a prospective applicant recognise that the page matches their search.",evaluation:"Compare relevant search queries and the usefulness of the landing page; a high position alone does not prove the information meets the user's need."}),
 lesson({id:"layout",title:"Give the page breathing room",skill:"usability",
  lines:["White space is empty space around page elements; it need not be white.","Grouping related items helps readers scan a page.","Alignment gives the page a predictable structure."],
  example:"A college page puts the course title, dates and Apply button together. A gap separates this group from unrelated news, making the application section easier to spot.",support:"Look for items that belong together. Can you recognise that group quickly?",
  question:"Which change best helps someone scan course information?",answers:["Group course details together and separate unrelated news","Place every heading and button at a different angle","Remove every gap so more items fit"],feedback:"Grouping, spacing and consistent alignment can make relationships clearer. More empty space is not automatically better.",pairs:[["White space","Space separating or surrounding elements"],["Alignment","Placing elements along a consistent line"]],analysis:"The gap separates application details from news, reducing the effort needed to identify the relevant section.",evaluation:"Prefer the clearer grouping if users find the task more easily, but check that important details are not pushed out of view."}),
 lesson({id:"navigation",title:"Keep navigation predictable",skill:"usability",
  lines:["Navigation is how users move between pages or sections.","Consistent names and positions help people recognise familiar actions.","A useful link says where it leads."],
  example:"On one site, 'Courses' stays in the same menu position. On another, the same section changes between 'Study', 'Offer' and an unlabelled icon.",support:"Follow the same task through two pages and compare the menu labels.",
  question:"Which design reduces the need to relearn navigation?",answers:["Keep the Courses label and position consistent","Rename the same link on each page","Use only symbols without clear names"],feedback:"Predictable navigation helps users transfer what they learned on one page to another.",pairs:[["Navigation","Routes between pages or sections"],["Consistency","Similar actions behave in familiar ways"]],analysis:"Changing the same label can make applicants stop and search again, increasing effort during the task.",evaluation:"Consistency is useful, but compare whether the menu also gives access to the information the audience needs."}),
 lesson({id:"contrast",title:"Make information visible",skill:"accessibility",wai:true,
  lines:["Contrast is the difference between foreground and background colours.","Text needs enough contrast to remain readable.","Do not rely on colour alone to communicate a result."],
  example:"A form marks an error with red text and the words 'Enter a date'. Another form shows only a red border, leaving some visitors unsure what needs correcting.",support:"Imagine you cannot distinguish the colours. Is the message still understandable?",
  question:"Which error message gives a useful signal beyond colour?",answers:["A clear written explanation beside the field","A red border with no explanation","A subtle change from pale green to pale red"],feedback:"A written message communicates meaning without requiring the user to distinguish colours. Contrast still needs checking separately.",pairs:[["Contrast","Difference between foreground and background"],["Colour-only cue","Meaning communicated only by a colour change"]],analysis:"The written instruction identifies the problem, helping the visitor correct it without interpreting colour.",evaluation:"The message is more understandable, but check its contrast and whether assistive technology announces it."}),
 lesson({id:"text-alternative",title:"Explain an important image",skill:"accessibility",wai:true,
  lines:["A text alternative conveys an image's meaning or function.","Useful wording depends on the image's purpose on that page.","Decorative images should not add unnecessary spoken descriptions."],
  example:"An image button shaped like a magnifying glass opens search. Its accessible name 'Search courses' explains the action more clearly than 'small black icon'.",support:"Ask what the user needs to know or do, not just what the picture looks like.",
  question:"What is the most useful name for an image button that searches courses?",answers:["Search courses","Small black icon","Picture number seven"],feedback:"A functional image needs a name describing its action. Informative images instead need an appropriate equivalent for their information.",pairs:[["Functional image","An image used to perform an action"],["Text alternative","Wording conveying the relevant meaning or function"]],analysis:"A meaningful button name lets a screen-reader user recognise the search action without seeing the icon.",evaluation:"A good name removes one barrier; it does not prove that the search form or results are fully accessible."}),
 lesson({id:"typography",title:"Make the words easy to read",skill:"usability",
  lines:["Typography concerns how text is presented.","Readable size, spacing and headings help people follow information.","Decoration should not hide the message."],
  example:"Website A uses descriptive headings and short paragraphs for course fees. Website B presents the same fees in tiny text over a patterned photograph.",support:"Find one important sentence. Can you read it without struggling or guessing its place?",
  question:"Which observation is useful when reviewing typography?",answers:["Important fee information stays readable when text is enlarged","The designer used the greatest number of fonts","Every paragraph is written in capitals"],feedback:"Judge typography through readability and structure, not the number of decorative styles.",pairs:[["Typography","Presentation of written text"],["Heading","A label identifying a section of content"]],analysis:"Clear headings help applicants find the fees section instead of reading every paragraph.",evaluation:"Readable text helps this audience, but check mobile layout and enlargement before drawing a wider conclusion."}),
 lesson({id:"accurate-content",title:"Check that the information helps",skill:"evidence",
  lines:["Content should be relevant, understandable and accurate.","An attractive page can still give outdated information.","Check important claims against a reliable source."],
  example:"Two course pages look professional. One shows last year's application deadline; the other clearly labels the current year and links to the admissions guidance.",support:"Look for the date, the source and whether the information answers the user's question.",
  question:"What matters most to an applicant checking a deadline?",answers:["Whether the published deadline applies to the current application year","How many decorative photos surround it","Whether the page uses your favourite typeface"],feedback:"Accuracy and relevance affect whether the visitor can make a sound decision. Appearance is not proof that a claim is current.",pairs:[["Accuracy","Information agrees with the relevant facts"],["Relevance","Information helps with the user's task"]],analysis:"An outdated deadline may cause an applicant to miss the opportunity even if the page is easy to navigate.",evaluation:"Prioritise correcting the deadline over decorative changes because its consequence for the applicant is greater."}),
 lesson({id:"media-size",title:"Balance image quality and waiting",skill:"performance",topicCode:"A2",
  lines:["Larger media files usually require more data to transfer.","Compression can reduce file size, sometimes reducing quality.","Choose enough quality for the image's purpose."],
  example:"A small course thumbnail uses a huge photograph file. A suitably resized version looks clear at the displayed size and transfers less data to a visitor's phone.",support:"Distinguish the displayed size on screen from the amount of data in the file.",
  question:"Which is a sensible first improvement for an oversized thumbnail?",answers:["Resize and compress it, then check quality and loading","Use an even larger file regardless of display size","Remove all written information instead"],feedback:"A proportionate image can reduce transfer work while preserving the detail users need. Measure the outcome rather than assuming a speed gain.",pairs:[["File size","Amount of data stored in a file"],["Compression","Representing data using less storage"]],analysis:"Less image data may reduce waiting on a slow connection, helping the visitor reach course information sooner.",evaluation:"Keep the smaller image if measured loading improves and useful detail remains; excessive compression may undermine the purpose."}),
 lesson({id:"server-client",title:"Where does the work happen?",skill:"performance",topicCode:"A2",
  lines:["Client-side work happens in the user's browser.","Server-side work happens on the website's server.","Either side can contribute to a slow response."],
  example:"A browser opens a menu locally, while the server searches a course database. A slow database response and a busy browser are different possible causes of delay.",support:"The client is the visitor's side; the server provides shared services and data.",
  question:"Where does a server-side course database search run?",answers:["On the website's server","Only inside the visitor's mouse","Inside a printed course prospectus"],feedback:"Server-side processing runs on the server. Browser processing runs on the client; they often cooperate to complete a task.",pairs:[["Client-side","Work performed in the browser"],["Server-side","Work performed by the website's server"]],analysis:"Moving a calculation to the browser may reduce a server request but increase work on a lower-powered phone.",evaluation:"Choose based on security, device and measured performance needs, not a claim that one side is always faster."}),
 lesson({id:"performance-evidence",title:"Find what causes the wait",skill:"performance",topicCode:"A2",
  lines:["Connection speed, device processing and server demand can affect loading.","A browser cache can reuse previously downloaded resources.","Use comparable test conditions when comparing speed."],
  example:"A page loads quickly on its second visit because an image is cached. Comparing that visit with another site's first visit could give a misleading result.",support:"Record the device, connection and whether the page has been loaded before.",
  question:"Why might a second visit load faster without any website change?",answers:["The browser can reuse cached resources","The page has definitely become more accurate","The website has automatically earned a higher grade"],feedback:"Cached resources can avoid repeat transfers. The effect depends on what is cached and whether it can be reused.",pairs:[["Cache","Stored resources that may be reused"],["Server demand","Requests competing for server resources"]],analysis:"A cached image reduces repeat downloads, but a new visitor may still face the original transfer time.",evaluation:"Compare both fresh and repeat visits under similar conditions before judging which site performs better."}),
 lesson({id:"compatibility",title:"Try another screen and browser",skill:"performance",topicCode:"A2",
  lines:["Compatibility means working in the environments people use.","A page that works on one laptop may fail on a phone.","Test the task, not only a screenshot."],
  example:"A college page looks tidy on a laptop, but its Apply button is hidden behind a fixed banner on a small phone. The visitor can read the course but cannot apply.",support:"Check that controls can be reached and activated, as well as whether the text fits.",
  question:"Which test provides stronger compatibility evidence?",answers:["Complete the same task on the target phone and browser","Look only at a laptop screenshot","Assume all browsers behave identically"],feedback:"A real task tests operation as well as appearance. State which devices and browsers were checked; do not claim every environment was covered.",pairs:[["Compatibility","Working in the intended environments"],["Responsive layout","A layout adapting to available screen space"]],analysis:"A hidden button blocks the task even when the rest of the mobile page appears attractive.",evaluation:"Prioritise fixing the blocked action, then retest it on the devices used by the target audience."}),
);

export const unit6StudyBaseline: StudyQuestionKey[] = [
  choice("baseline-purpose-v1","purpose","A bus website should mainly help passengers to…",["Find routes and departure times","View the designer's favourite animation","Change the company's staffing rota","I'm not sure yet"],"The audience is passengers; the main task is finding travel information."),
  choice("baseline-usability-v1","usability","Which button label is clearest for finding a college course?",["Find a course","Things","Go somewhere","I'm not sure yet"],"A specific label helps a visitor predict what the button will do."),
  choice("baseline-access-v1","accessibility","Who might need to use a website without a mouse?",["Someone who uses a keyboard because of a disability","Only the website designer","Nobody: every visitor must use a mouse","I'm not sure yet"],"People use different input methods. A working website should not assume everyone can use a mouse."),
  choice("baseline-evidence-v1","evidence","What is the fairest way to compare two course websites?",["Try the same task on both and record what happens","Look only at which logo you prefer","Ask one designer which is best without trying them","I'm not sure yet"],"Comparable tasks and recorded observations give useful evidence for a judgement."),
];

export function studyContentFor(unitCode:string) {
  switch(unitCode){
    case "2":return databaseStudy;
    case "4":return programmingStudy;
    case "5":return dataModellingStudy;
    case "6":return {version:"u6-mini-v1",lessons:unit6StudyLessons,baseline:unit6StudyBaseline};
    case "9":return projectStudy;
    case "11":return securityStudy;
    case "16":return cloudStudy;
    case "19":return iotStudy;
    default:return undefined;
  }
}
