import {makeStudyPack} from "./mini-study-pack";
const accounts="https://www.ncsc.gov.uk/collection/small-organisations-guide-to-cyber-security/secure-your-important-online-accounts";
const backups="https://www.ncsc.gov.uk/collection/small-organisations-guide-to-cyber-security/backing-up-your-data";

export const securityStudy=makeStudyPack("11",[
 {id:"weakness",topic:"A1-A2",title:"Separate a threat from a weakness",skill:"threats",
  lines:["A threat is a possible cause of harm.","A vulnerability is a weakness that could be exploited.","The impact is the resulting harm to people or services."],
  example:"A fictional club shares one administrator password. That is a weakness; someone misusing it is a threat, and cancelled bookings could be an impact.",help:"Follow: cause of harm → weakness → consequence.",
  question:"Which item is the vulnerability in this example?",answers:["The shared administrator password","The loss of booking availability","The club's need to organise events"],feedback:"A shared privileged password is a weakness. The consequence is distinct from the weakness that enables it.",pairs:[["Vulnerability","A weakness that could be exploited"],["Impact","The resulting harm or disruption"]],analyse:"Sharing administrator access can make it harder to limit permissions and identify who changed bookings.",evaluate:"Separate accounts reduce this weakness, but they do not remove unrelated risks such as device failure."},
 {id:"risk",topic:"C1-C2",title:"Which risk needs attention first?",skill:"risk",
  lines:["Risk considers both the chance of an event and its impact.","A severe outcome is not the same as a likely outcome.","Use evidence about exposure and consequences to set priorities."],
  example:"A public booking server and an unplugged training computer have the same reported fault. Their exposure and effect on the club's work are different.",help:"Ask how the event could happen and what would be affected.",
  question:"What should guide the club's risk priority?",answers:["Evidence about likelihood and business impact","Only which device has the brightest screen","Only the number of characters in a fault report"],feedback:"Risk prioritisation needs context. A finding's name alone does not establish its likelihood or impact here.",pairs:[["Likelihood","How probable the event is"],["Impact","How serious its consequences would be"]],analyse:"The public server's exposure may increase opportunity for misuse, while an outage would interrupt bookings.",evaluate:"Prioritise using evidence, but record uncertainty rather than assigning confident scores without a basis."},
 {id:"permissions",topic:"A3-A5",title:"Give only the access needed",skill:"access",
  lines:["Authentication checks who someone is.","Authorisation determines what they may do.","Least privilege gives only the access needed for a task."],
  example:"A club volunteer signs in with their own account and can update bookings, but cannot open payroll files. Signing in does not grant access to everything.",help:"Who are you? is different from What may you do?",
  question:"Which permission best fits a volunteer updating bookings?",answers:["Access to bookings without unrelated payroll access","Administrator access to every service","A shared password for the payroll manager's account"],feedback:"Permissions should match the role's task. A valid login does not justify access to unrelated information.",pairs:[["Authentication","Checking an identity"],["Authorisation","Deciding permitted actions"]],analyse:"Restricting payroll access reduces the information exposed if a volunteer account is misused.",evaluate:"Check that required work remains possible, and review permissions when the person's role changes."},
 {id:"sign-in",topic:"A3-A5",title:"Add another sign-in factor",skill:"authentication",sources:[accounts],
  lines:["Multi-factor authentication combines different types of identity evidence.","A password plus an approved device check can add protection.","Two passwords alone are not two different factor types."],
  example:"A club account asks for a password and confirmation using an approved authenticator. Knowing the password alone should not complete that configured sign-in.",help:"Factors can involve something known, something held or a physical characteristic.",
  question:"Which example combines different factor types?",answers:["A password and an approved authenticator device","Two different passwords","A password entered twice into the same form"],feedback:"A password is knowledge; possession of an approved authenticator is a different factor. The strength of the method and recovery process still matter.",pairs:[["Knowledge factor","Something the user knows"],["Possession factor","Something the user holds or controls"]],analyse:"A second factor can reduce the chance that a stolen password alone results in account access.",evaluate:"It is additional protection, not a guarantee; consider phishing resistance and secure recovery arrangements."},
 {id:"recovery",topic:"D1-D2",title:"Check that recovery works",skill:"recovery",sources:[backups],
  lines:["A backup is a copy kept for recovery.","A restore test checks that useful data can be recovered.","Protect backups from the same failure affecting the original."],
  example:"The club backs up bookings, then restores a harmless test copy in an approved test area. A success message alone would not show that all needed bookings can be read.",help:"A backup is useful only if the right information can be recovered when needed.",
  question:"What gives stronger recovery evidence?",answers:["Restoring a test copy and checking required information","Assuming a backup icon means everything is safe","Keeping the only copy on the failing original device"],feedback:"Recovery should be checked, including the information needed to resume work. Keep tests isolated from live records.",pairs:[["Backup","A copy retained for recovery"],["Restore test","A check that recovery produces usable information"]],analyse:"A separate protected backup may allow bookings to be recovered after the original system fails.",evaluate:"Consider how much recent work could be lost and how long restoration takes, not only whether a copy exists."},
 {id:"evidence",topic:"E1-E2",title:"A log entry is not the whole story",skill:"evidence",
  lines:["An observation is what the evidence directly shows.","An inference is a possible explanation of it.","Preserve originals and consider alternative explanations."],
  example:"A supplied fictional log shows a failed sign-in followed by a successful one. It could be a user correcting a typo; these entries alone do not prove account theft.",help:"Work only with teacher-provided evidence or an explicitly authorised test environment.",
  question:"What can these two entries establish by themselves?",answers:["A failed attempt was followed by a successful attempt","An account was definitely stolen","Every other account is safe"],feedback:"The entries show events, not a proven cause. Correlate additional authorised evidence before making a stronger conclusion.",pairs:[["Observation","What the evidence directly shows"],["Inference","An explanation drawn from evidence"]],analyse:"Related timestamps and device records may strengthen or weaken an explanation of the sign-ins.",evaluate:"State confidence and limitations. Recommend proportionate checks without treating suspicion as established fact."},
]);
