import {makeStudyPack} from "./mini-study-pack";
import type {ShortStudyIdea} from "./mini-study-pack";

const unit6ExtensionIdeas: ShortStudyIdea[] = [
  {id:"requirements",topic:"B1",title:"Turn a client brief into website requirements",skill:"requirements",
    lines:["A website design starts from the client's purpose, audience and required features.","Constraints can include time, budget, devices, brand rules and legal responsibilities.","A useful requirement is specific enough to check later."],example:"A college wants prospective learners to find a course, compare entry requirements and submit an enquiry on mobile and desktop.",help:"Rewrite vague wishes as testable statements about what the user must be able to do.",question:"Which requirement is most testable?",answers:["A visitor can find a course and its entry requirements on mobile and desktop","Make the website nice","Use lots of modern effects"],feedback:"A testable requirement states a user task and the environments in which it should work.",pairs:[["Requirement","A specific need the website should meet"],["Constraint","A limit affecting the design or implementation"]],analyse:"Precise requirements let the team connect later design and test evidence to the client's real needs.",evaluate:"Prioritise requirements by user and client impact when constraints prevent every desirable feature."},
  {id:"wireframes-sitemap",topic:"B1",title:"Plan pages, routes and layouts before coding",skill:"design",
    lines:["A site map shows how pages are organised and linked.","A wireframe shows the planned placement of content and controls.","A prototype can make important interactions easier to review before full development."],example:"A course site map links Home to Courses, Course details and Contact. A mobile wireframe keeps the course-search action near the top.",help:"Trace one realistic user journey through the design before opening an editor.",question:"What does a site map mainly show?",answers:["The structure and links between pages","The exact final image compression setting","Only the website's colour palette"],feedback:"A site map communicates page hierarchy and navigation relationships.",pairs:[["Wireframe","A planned page layout"],["Site map","A diagram of page structure and navigation"]],analyse:"A design review can find missing routes or buried actions before those problems are repeated across coded pages.",evaluate:"Revise designs from evidence and feedback rather than treating the first sketch as fixed."},
  {id:"assets-legal",topic:"B1",title:"Plan assets, copyright and data handling",skill:"legal-ethical",
    lines:["Website assets need suitable ownership or permission for use.","Forms should collect only data needed for a clear purpose.","Design decisions should consider privacy, accessibility and other relevant legal or ethical constraints."],example:"A contact form asks for name, email and enquiry text because those fields are needed to respond. It does not request unrelated sensitive information.",help:"For each asset or field, ask why it is needed and what permission or protection applies.",question:"Which form design best follows data minimisation?",answers:["Collect only information needed to answer the enquiry","Collect every detail in case it becomes useful later","Ask for unrelated private information by default"],feedback:"Data minimisation means collecting information that is relevant and necessary for the stated purpose.",pairs:[["Copyright","Rights controlling use of creative work"],["Data minimisation","Collecting only information needed for the purpose"]],analyse:"Unnecessary data collection increases risk without helping the user's task.",evaluate:"Check current organisational and legal guidance rather than assuming one design rule covers every situation."},
  {id:"semantic-html",topic:"B2",title:"Build a clear semantic HTML structure",skill:"html",
    lines:["HTML gives content structure and meaning.","Semantic elements such as header, nav, main and footer describe the role of page regions.","Headings should form a logical outline rather than being chosen only for visual size."],example:"A course page uses one main heading for the course title, section headings for entry requirements and fees, and a nav element for site navigation.",help:"Describe what each block means before deciding how it should look.",question:"Which element is most suitable for the page's primary navigation links?",answers:["nav","strong","br"],feedback:"The nav element identifies a major navigation region.",pairs:[["HTML","Defines document structure and meaning"],["Semantic element","Communicates the role of content"]],analyse:"Semantic structure helps browsers and assistive technologies understand the page beyond its visual appearance.",evaluate:"Use semantics that match the content; adding semantic elements randomly does not improve structure."},
  {id:"links-forms-tables",topic:"B2",title:"Use links, forms and tables for the right jobs",skill:"html",
    lines:["Links move users to another resource or location.","Forms collect user input using controls with clear labels.","Tables are for genuinely tabular data, not for general page layout."],example:"A timetable uses a table with headings for day and time, while a contact form uses labelled inputs and a submit button.",help:"Choose an element because its meaning matches the content, not because it happens to position things on screen.",question:"When is a table most appropriate?",answers:["For data with meaningful rows and columns","For arranging every page into visual columns","For replacing all navigation links"],feedback:"Tables are intended for tabular relationships between data values.",pairs:[["Form label","Identifies the purpose of an input"],["Anchor link","Moves to a resource or page location"]],analyse:"Correct elements improve clarity and reduce the amount of custom code needed to reproduce built-in behaviour.",evaluate:"Test forms with keyboard navigation, error messages and realistic input before judging them usable."},
  {id:"css-box-layout",topic:"B2",title:"Control spacing and layout with CSS",skill:"css",
    lines:["CSS controls presentation separately from HTML structure.","The box model includes content, padding, border and margin.","Modern layout tools such as flexbox and grid can adapt groups of elements without changing their semantic order."],example:"A card has padding inside its border and margin outside it. A grid changes from three columns on wide screens to one column on narrow screens.",help:"When spacing looks wrong, identify whether the space belongs inside or outside the border.",question:"Which box-model property adds space inside an element's border?",answers:["Padding","Margin","URL"],feedback:"Padding creates space between content and the border.",pairs:[["Padding","Space inside the border"],["Margin","Space outside the border"]],analyse:"Separating structure from presentation makes responsive and visual changes easier without rewriting the page's meaning.",evaluate:"Prefer the simplest layout technique that meets the design and remains understandable across target screens."},
  {id:"responsive-design",topic:"B2-C2",title:"Adapt the website to different screens",skill:"responsive",
    lines:["Responsive design adapts layout to available space rather than assuming one screen size.","Flexible sizing and media queries can change layout at useful breakpoints.","Important content and controls must remain reachable, readable and usable."],example:"A desktop navigation row becomes a compact menu on a phone, while course cards stack into one readable column.",help:"Resize the viewport and complete the same user task rather than checking appearance alone.",question:"What is the strongest mobile check?",answers:["Complete the intended task on the target screen size","Check only whether the logo fits","Assume a desktop layout will automatically work"],feedback:"Responsive quality is demonstrated by successful tasks across the intended environments.",pairs:[["Media query","Applies styles under defined conditions"],["Responsive layout","Adapts to available screen space"]],analyse:"A layout can appear tidy yet still fail if an important control becomes hidden or too difficult to activate.",evaluate:"Choose breakpoints from content and task behaviour, not simply from one designer's device sizes."},
  {id:"javascript-events",topic:"C1",title:"Make interactions respond to events",skill:"javascript",
    lines:["Client-side JavaScript can respond to events in the browser.","An event listener connects an event such as a click or input change to a function.","Interactive behaviour should support the user's task rather than exist only for decoration."],example:"Selecting a course filter triggers a function that updates visible course cards without requiring a new page load.",help:"Name the event, the function that handles it and the user-visible result.",question:"What does an event listener do?",answers:["Runs defined code when a relevant event occurs","Stores every website image","Replaces the need for HTML"],feedback:"An event listener connects a browser event to the code that should respond.",pairs:[["Event","Something that happens, such as a click"],["Handler","Code that responds to the event"]],analyse:"Event-driven behaviour can make a task faster, but only if the result remains understandable and accessible.",evaluate:"Keep essential information available when possible and test the interaction with keyboard as well as pointer input."},
  {id:"javascript-validation",topic:"C1",title:"Use client-side validation without trusting it alone",skill:"javascript",
    lines:["Client-side validation can give immediate feedback before a form is sent.","Decisions, loops and functions support richer interactions.","Server-side checks are still needed for data that must be trusted because browser code can be bypassed."],example:"A form warns immediately when an email field is empty, while the server still validates submitted data before saving it.",help:"Client-side checks improve the experience; trusted processing must still verify the data at the receiving side.",question:"Why should important server processing validate data again?",answers:["Client-side checks can be bypassed or altered","JavaScript can never read form values","Validation is only about colour"],feedback:"Browser-side checks help users but cannot be treated as the sole trusted control.",pairs:[["Client-side validation","Immediate checks in the browser"],["Server-side validation","Trusted checks when processing submitted data"]],analyse:"Using both layers improves feedback while preventing the server from relying on untrusted browser behaviour.",evaluate:"Validate according to actual requirements and avoid rejecting legitimate input with unnecessarily strict rules."},
  {id:"publish-host",topic:"C2",title:"Publish a working site and verify the deployed version",skill:"publishing",
    lines:["Publishing moves website files to a host where intended users can access them.","Relative paths, case sensitivity and environment differences can break a site that worked locally.","The deployed website needs its own functional checks."],example:"An image called Logo.png works on a local case-insensitive system but fails after deployment because the HTML requests logo.png.",help:"Test the live URL, not only the local development copy.",question:"What should happen after deployment?",answers:["Repeat key checks on the hosted version","Assume the hosted version is identical without testing","Delete the local test evidence"],feedback:"Deployment introduces environment differences, so critical tasks should be verified on the live host.",pairs:[["Hosting","Providing the website from a server or platform"],["Deployment check","Testing the published version"]],analyse:"A deployment defect can block users even when the development copy passed all local tests.",evaluate:"Use a repeatable deployment checklist for links, assets, forms, compatibility and required security settings."},
  {id:"user-testing",topic:"C3-C5",title:"Use user testing to find real barriers",skill:"testing",
    lines:["User testing observes people attempting realistic tasks.","Record what they do, where they hesitate and whether they complete the task.","Feedback is stronger when it is linked to an observed problem rather than a general preference."],example:"Three learners try to find entry requirements on a phone. Two miss the menu label, so the label is revised and the same task is retested.",help:"Give a goal, not step-by-step instructions, so the test reveals whether the interface communicates clearly.",question:"Which result is strongest evidence for a navigation problem?",answers:["Several target users cannot find the required page without help","The developer personally likes the menu","A different website uses blue"],feedback:"Observed task difficulty from target users is relevant evidence for usability refinement.",pairs:[["User test","Observation of a realistic task"],["Retest","Repeating the check after a change"]],analyse:"Repeated hesitation at the same label suggests a design issue rather than an isolated preference.",evaluate:"Use enough varied evidence for the claim you make and record limitations such as device and sample size."},
  {id:"optimise-site",topic:"C3-C5",title:"Optimise the site using measured evidence",skill:"optimisation",
    lines:["Optimisation should target a demonstrated weakness.","Changes can improve loading, usability, accessibility or maintainability.","Measure or retest after the change so the improvement has evidence."],example:"A large hero image is resized and compressed, then fresh-load transfer size and visual quality are compared before and after.",help:"Write the problem and the measure first; then choose the improvement.",question:"What makes an optimisation claim convincing?",answers:["Comparable evidence before and after the change","A claim that the page feels faster","Changing several things without recording the result"],feedback:"Before-and-after evidence connects the change to a measurable outcome.",pairs:[["Optimisation","A targeted improvement based on evidence"],["Retest","Checks the effect after the change"]],analyse:"Reducing transfer size can improve loading but too much compression may damage image usefulness.",evaluate:"Choose the improvement with the strongest benefit for the audience and requirements, not simply the largest technical change."},
  {id:"challenge-audit",topic:"C3-C5",title:"Challenge: audit a website from evidence",skill:"analysis",
    lines:["A strong audit connects features to effects on a named audience.","Combine design, accessibility, performance and task evidence.","Separate what was observed from what is inferred."],example:"The Apply button is hidden on a 360px screen and two test users cannot complete the task. Explain the effect, identify the responsive defect and propose a testable correction.",help:"Use: evidence → effect on user → likely cause → improvement → retest.",question:"Which statement is analytical?",answers:["The hidden Apply button blocks the mobile task, so the responsive layout should be corrected and retested","The page has a button","I prefer a different colour"],feedback:"Analysis links evidence to user impact and a reasoned correction.",pairs:[["Observation","What was actually seen or measured"],["Analysis","Explains why that evidence matters"]],analyse:"Combine multiple evidence sources when they support the same usability or performance issue.",evaluate:"Prioritise barriers that prevent important user tasks before lower-impact cosmetic changes."},
  {id:"supported-evaluation",topic:"C3-C5",title:"Stretch: evaluate and defend website improvements",skill:"evaluation",
    lines:["Evaluation weighs strengths and weaknesses against the client requirements.","A supported judgement uses test results, user evidence and known constraints.","A limitation states where the evidence does not justify a wider claim."],example:"The redesigned navigation improved course-finding on the tested phones, but only two browsers were checked, so compatibility conclusions remain limited.",help:"For every judgement, name the requirement, evidence and an important limitation or trade-off.",question:"Which conclusion is best supported?",answers:["The tested navigation improved course finding, but browser coverage is still limited","The website is perfect because the homepage loads","The website is bad because I dislike the font"],feedback:"A balanced evaluation explains what the evidence supports and what it does not.",pairs:[["Judgement","A conclusion supported by evidence"],["Limitation","A boundary on how far the conclusion can be applied"]],analyse:"A site can improve one requirement while still needing work in another area.",evaluate:"Prioritise future improvements by audience impact, client value, risk and evidence."},
];

export const unit6ExtensionStudy = makeStudyPack("6", unit6ExtensionIdeas);
