import {makeStudyPack} from "./mini-study-pack";

export const projectStudy=makeStudyPack("9",[
 {id:"project",topic:"A1",title:"A project has an end point",skill:"project",
  lines:["A project is temporary work aimed at a defined outcome.","Routine operations keep an existing service running.","Both need resources, but they have different purposes."],
  example:"Installing a new booking system is a project. Processing bookings each day after launch is routine operation of that system.",help:"Look for a defined change, beginning and end.",question:"Which activity is a project?",answers:["Installing a new booking system by an agreed date","Processing the usual bookings every day","Repeating the same daily backup indefinitely"],feedback:"The installation has a defined outcome and completion point. Routine activities continue to operate the service.",pairs:[["Project","Temporary work towards a defined outcome"],["Operation","Ongoing work running an existing service"]],analyse:"A clear end point helps the team plan when the new service should be handed over.",evaluate:"Judge both delivery and readiness for operation; installation alone may not mean users can work successfully."},
 {id:"scope",topic:"B1",title:"Agree what is included",skill:"scope",
  lines:["Scope sets the boundaries of the work.","A new request may change time, cost or quality needs.","Assess and agree a change before adding it to the plan."],
  example:"A booking project covers room reservations. Halfway through, someone asks for payroll too. The team checks the extra work rather than silently adding it.",help:"State what is included and what is outside the current agreement.",question:"What is the sensible response to the payroll request?",answers:["Assess its effect and agree whether the scope should change","Add it without adjusting any plans","Assume it cannot affect the delivery date"],feedback:"Change can be useful, but its effect on the agreed work and constraints needs consideration.",pairs:[["Scope","The agreed boundaries of the work"],["Change control","Assessing and agreeing changes to the plan"]],analyse:"Payroll adds development and testing work, which can delay the original booking outcome.",evaluate:"Consider the benefit against the extra cost and delay; rejecting every change is not automatically the best decision."},
 {id:"success",topic:"B2-B3",title:"Make success checkable",skill:"requirements",
  lines:["Success criteria describe how an outcome will be judged.","A measurable criterion can be checked with evidence.","Agree the criteria with the people who need the result."],
  example:"The booking team agrees that an authorised receptionist can reserve an available room without a duplicate booking. They can demonstrate and test that task.",help:"Replace 'works well' with a specific observable result.",question:"Which criterion can be tested?",answers:["An authorised receptionist can reserve a free room without a duplicate booking","The project feels impressive","Everyone will like every design decision"],feedback:"A specific task and expected result allow verification. Vague praise does not establish success.",pairs:[["Success criterion","A checkable condition for judging the outcome"],["Evidence","Information supporting a conclusion"]],analyse:"Testing against agreed criteria can reveal a missing booking control before handover.",evaluate:"Passing this task is useful evidence, but check other agreed criteria before judging the whole project successful."},
 {id:"dependency",topic:"C1-C2",title:"Some tasks depend on others",skill:"planning",
  lines:["A dependency links tasks that rely on each other.","A milestone marks an important point in the plan.","Delays to a prerequisite can affect later work."],
  example:"The team must agree the room-booking rules before testing those rules. A late decision can leave the planned test blocked even when the tester is available.",help:"Ask what must be ready before this task can finish.",question:"What is the dependency in this example?",answers:["Testing relies on agreed booking rules","The tester prefers a blue calendar","Every task must have the same duration"],feedback:"Dependencies describe reliance between tasks. They help explain why one delay may affect other work.",pairs:[["Dependency","A reliance between tasks"],["Milestone","An important point in a project plan"]],analyse:"Delaying the rules decision may postpone testing and reduce time available for correcting faults.",evaluate:"Review the whole dependency chain before moving dates; adding people may not remove a missing decision."},
 {id:"risk-issue",topic:"C1-C2",title:"A risk is not yet an issue",skill:"risk",
  lines:["A risk is an uncertain event that could affect the project.","An issue is a problem that has already occurred.","Record an owner and a suitable response."],
  example:"A supplier might deliver late: that is a risk. When the agreed delivery date is missed and equipment is unavailable, the team has an issue to manage.",help:"Ask whether the problem might happen or has happened.",question:"Which statement describes an issue?",answers:["The required equipment has not arrived by its agreed date","The supplier might be late next month","A delay is possible but has not happened"],feedback:"An issue is current; a risk concerns uncertainty. Both need proportionate monitoring and action.",pairs:[["Risk","An uncertain event that may affect the project"],["Issue","A problem that has already occurred"]],analyse:"A late delivery can block installation, affecting later tests and the agreed handover date.",evaluate:"Compare response options using cost, time and remaining risk rather than choosing the first available workaround."},
 {id:"review",topic:"D1",title:"Learn from the outcome",skill:"evaluation",
  lines:["A review compares the outcome with agreed objectives.","Separate the product's success from how the work was managed.","Use evidence to recommend a specific improvement."],
  example:"The booking system passes its task tests but is delivered late. The team can recognise the useful result while examining why planning underestimated testing time.",help:"A project can have strengths and weaknesses at the same time.",question:"Which review is best supported?",answers:["Task tests passed, but the late delivery suggests planning needs improvement","Everything was perfect because the team worked hard","Nothing worked because one date was missed"],feedback:"A balanced review uses evidence about both the outcome and the process. Effort alone does not establish effectiveness.",pairs:[["Outcome review","Checking what was delivered against objectives"],["Lessons learned","Evidence-based improvements for future work"]],analyse:"Underestimating testing left too little time to correct defects, contributing to late delivery.",evaluate:"Recommend an evidence-based allowance for testing and review whether it would address the cause of delay."},
]);
