import {makeStudyPack} from "./mini-study-pack";

export const cloudStudy=makeStudyPack("16",[
 {id:"service",topic:"A1-A2",title:"Choose the kind of cloud service",skill:"models",
  lines:["Cloud services provide computing resources over a network.","SaaS supplies an application; IaaS supplies infrastructure such as virtual machines.","The customer manages different responsibilities in each model."],
  example:"A charity can use a hosted document editor or run its own application on a rented virtual machine. The second option leaves more software administration to the charity.",help:"Ask which parts the provider runs and which the customer must manage.",question:"Which is an example of SaaS?",answers:["Using a hosted document-editing application","Managing an operating system on a rented virtual machine","Buying paper notebooks for volunteers"],feedback:"SaaS provides software as a service. It does not remove the customer's responsibility for suitable accounts, permissions and use.",pairs:[["SaaS","A hosted application supplied as a service"],["IaaS","Computing infrastructure supplied as a service"]],analyse:"A hosted editor can reduce maintenance work, helping a small team spend time on its main task.",evaluate:"Check required features and control needs; less maintenance does not automatically mean the service is suitable."},
 {id:"needs",topic:"A3-A5",title:"Start with the users' needs",skill:"requirements",
  lines:["A requirement states what a service needs to do.","A constraint limits the possible choices.","Choose tools against actual tasks and working conditions."],
  example:"Volunteers need to edit a rota using older phones. Some have unreliable internet, so the charity checks device support and what happens when a connection drops.",help:"A useful requirement can be checked in a realistic task.",question:"Which is a testable requirement?",answers:["Volunteers can edit the rota on their supported phones","The service must be amazing","The logo must make everyone happy"],feedback:"A testable requirement specifies an observable capability. Vague praise cannot establish whether the service meets the need.",pairs:[["Requirement","Something the service needs to do"],["Constraint","A limit on the available choices"]],analyse:"If the editor does not work on volunteers' phones, a useful feature list may still fail the real task.",evaluate:"Choose the service supported by user tests and explain important limitations such as offline behaviour."},
 {id:"sharing",topic:"B1-B2",title:"Sharing is a permission decision",skill:"permissions",
  lines:["A permission controls actions such as reading or editing.","Different folders can need different access rules.","Share only with the people who need the information."],
  example:"The charity makes event leaflets public, lets volunteers edit the rota, and restricts staff records. One open link for every folder would ignore these different needs.",help:"List the person, the resource and the action they need.",question:"Which permission fits a volunteer updating the rota?",answers:["Edit the rota without access to confidential staff files","Edit every file owned by the charity","Share all staff files publicly"],feedback:"Match the permission to the task. Test that both allowed access and denied access work as intended.",pairs:[["Read permission","Allows viewing information"],["Edit permission","Allows changing information"]],analyse:"Separate folder permissions can limit unintended disclosure while supporting the volunteer's work.",evaluate:"Check sharing links and inherited permissions, not just the labels shown in one folder."},
 {id:"versions",topic:"C1-C2",title:"Keep track of shared changes",skill:"collaboration",
  lines:["Collaboration means working together on shared material.","Version history can record earlier states of a document.","Review a previous version before restoring it."],
  example:"Two volunteers edit a rota and a shift disappears. The team inspects available version history to identify the change rather than immediately replacing everyone's recent work.",help:"Consider who changed what, and which later edits must be retained.",question:"What is a sensible first use of version history?",answers:["Inspect earlier states to understand the change","Assume every earlier version is better","Restore the oldest copy without checking other edits"],feedback:"History can help investigate and recover changes. Retention and restore behaviour vary by service and should be tested.",pairs:[["Collaboration","People working on shared material"],["Version history","A record of earlier document states"]],analyse:"Inspecting changes can reduce accidental loss of other volunteers' valid edits.",evaluate:"Useful history supports recovery, but verify how long versions are retained and who can restore them."},
 {id:"sync",topic:"C1-C2",title:"Sync and backup are different",skill:"recovery",
  lines:["Synchronisation keeps copies updated with changes.","A backup retains information for recovery.","A deletion may synchronise too; check the recovery arrangements."],
  example:"Deleting a test file on one device also removes it from a synchronised folder elsewhere. The team checks the service's recovery tools instead of assuming another synced copy is protected.",help:"Ask whether the same mistake or failure could affect every copy.",question:"Why is a second synchronised copy not always enough for recovery?",answers:["The same deletion may be copied to it","Synchronised files can never change","Only printed files can be backed up"],feedback:"Sync may propagate unwanted changes. Establish and test recovery independently of assumptions about multiple copies.",pairs:[["Synchronisation","Keeping copies updated with changes"],["Backup","A copy retained for recovery"]],analyse:"Propagation of a deletion can affect several devices, so more synced copies may not solve that failure.",evaluate:"Judge recovery by a successful isolated restore test and its limitations, not only by counting copies."},
 {id:"handover",topic:"C3-C5",title:"Make the service usable after handover",skill:"evaluation",
  lines:["A handover gives users the information needed to operate the service.","Explain routine access, support and recovery in plain language.","Evaluate the result against the original requirements."],
  example:"The charity asks a volunteer to follow its new guide and update a test rota. The volunteer's questions reveal a missing instruction about requesting access.",help:"A useful guide should let its intended reader complete a real task.",question:"Which evidence best supports a judgement about the guide?",answers:["A target user completes the task using it and their difficulties are recorded","Its author says it is perfect","The cover uses an expensive-looking photograph"],feedback:"Observed use provides evidence about suitability. State the tested task and audience rather than claiming universal success.",pairs:[["Handover","Passing on operation and support information"],["Evaluation","A judgement supported by evidence"]],analyse:"A missing access step can stop a volunteer before editing begins, even when later instructions are clear.",evaluate:"Prioritise adding that step, then repeat the task with an intended user before claiming the guide improved."},
]);
