from pathlib import Path
p=Path('src/lib/starting-point.ts')
items=[
('files','Which filename makes a report easiest to find?',['Network_report_v1.docx','Document7.docx','Untitled.docx'],'Use a descriptive name and a version number so you can find the right file later.','Which name clearly identifies a revised budget?',['Budget_v2.xlsx','Book1.xlsx','New file.xlsx']),
('backup','A backup is…',['A separate recoverable copy','Renaming the original file','A shortcut to the original'],'Keep a separate copy and check that you can restore it. A shortcut is only a link.','Your laptop fails. What helps recover your work?',['A tested copy on another device','A renamed file on that laptop','A desktop shortcut']),
('privacy','Who should see a student’s private record?',['Authorised staff who need it','Everyone in the class','Anyone with the link'],'Give access only to people who need the information for their role.','Who needs access to payroll records?',['Authorised payroll staff','Every customer','All website visitors']),
('security','An unexpected email asks for your password. You…',['Verify through a trusted channel','Reply with the password','Forward it to classmates'],'Do not send passwords. Contact the organisation using a known address or number, not the email link.','A message claims your account will close. First…',['Check using the official app','Enter your password in its link','Send your login to the sender']),
('numbers','Four tickets cost £5 each. Total?',['£20','£9','£25'],'Multiply the number of items by the price of one item: 4 × 5 = 20.','Three items cost £7 each. Total?',['£21','£10','£28']),
('logic','Access needs a valid password AND code. You need…',['Both','Either one','Neither'],'AND means both conditions must be true. OR means at least one condition must be true.','A discount needs membership AND a voucher. You have only membership.',['No discount yet','Discount applies','Voucher is irrelevant']),
('sequence','Before dividing by a typed number, first…',['Check it is a non-zero number','Display the final answer','Delete the result'],'Check the input before using it. Division by zero is not valid.','Before calculating with an entered age, first…',['Check the input is a valid number','Format the result','Print a receipt']),
('data','Which value is a whole number?',['12','12.5','Twelve people'],'Whole-number values have no fractional part. Text labels are a different kind of data.','Which value is suitable for counting seats?',['24','24.8','Twenty-four chairs']),
('evidence','A claim has no source. What should you do?',['Check a reliable source','Treat it as proven','Copy it without checking'],'Check who produced the information and whether evidence supports the claim.','Two sites give different course dates. Check…',['The official course information','Which site has more pictures','Which date you prefer']),
('testing','After fixing a broken link, you should…',['Try the link again','Assume it now works','Change an unrelated page'],'Repeat the action that failed and check the expected result. A change alone does not prove a fix.','After correcting a calculation, you should…',['Test with a known expected answer','Only change its font','Skip running it'])]
import json
p.write_text('import type {StudyLesson,StudyQuestionKey,StudyGrade} from "./mini-study";\nexport const startingPointId="it-prerequisites-10-v1";\nconst items='+json.dumps(items,ensure_ascii=False)+' as const;\n'+'''export const startingPointQuestions:StudyQuestionKey[]=items.map(([skill,prompt,options,explanation])=>({id:`prereq:${skill}`,skill:`prereq-${skill}`,prompt,kind:"choice",options:[...options.map((text,i)=>({id:`o${i}`,text})),{id:"timeout",text:"Time expired — needs another check"}],answer:"o0",explanation}));
export const prerequisiteLessons:StudyLesson[]=items.map(([skill,,,explanation,prompt,options])=>({id:`prereq-${skill}-v1`,unitCode:"foundation",topicCode:"prerequisite",title:`Required skill: ${skill}`,skill:`prereq-${skill}`,lines:[explanation],example:"Apply the idea in the different example below.",support:explanation,analysis:"Explain why your answer fits the situation.",evaluation:"Explain when this approach would need another check.",sources:[],questions:[{id:`practice:${skill}`,skill:`prereq-${skill}`,prompt,kind:"choice",options:options.map((text,i)=>({id:`o${i}`,text})),answer:"o0",explanation}]}));
export function startingPointRoute(grade:StudyGrade){
 const timedOut=grade.feedback.filter(f=>f.selectedAnswer?.startsWith("Time expired")).length;
 if(timedOut)return `Needs another check · ${timedOut} timed out (not evidence of a missing skill)`;
 return grade.correct<5?"Required skills · support first":grade.correct<8?"Core · build confidence":"Stretch · extend your reasoning";
}
''',encoding='utf-8')
p=Path('src/lib/mini-study-server.ts');s=p.read_text();s='import {startingPointId,startingPointQuestions,prerequisiteLessons} from "./starting-point";\n'+s
s=s.replace('thinking:content.thinking,','thinking:content.thinking,secondsPerQuestion:content.secondsPerQuestion,')
s=s.replace('if(completedToday?.reward && !continueToday)', 'if(completedToday?.reward && !continueToday && sessions.some(s=>s.lesson_id===startingPointId&&s.status==="completed"))')
s=s.replace('if(!legacy && !history.some(h=>h.kind==="baseline"))','if(!sessions.some(s=>s.lesson_id===startingPointId&&s.status==="completed"))')
s=s.replace('nextStudyLesson(content.lessons,history)', 'nextStudyLesson([...prerequisiteLessons.filter(l=>history.some(h=>h.kind==="baseline"&&h.feedback.some(f=>!f.correct&&f.skill===l.skill))),...content.lessons],history)')
s=s.replace('const history=studyHistoryForUnit(sessions,context.unitId);','const history=studyHistoryForUnit(sessions.filter(s=>s.unit_id===context.unitId||s.lesson_id===startingPointId||s.lesson_id.startsWith("prereq-")).map(s=>({...s,unit_id:context.unitId})),context.unitId);')
s=s.replace('.eq("unit_id",context.unitId).eq("status","completed");','.eq("status","completed");')
s=s.replace('const history=studyHistoryForUnit((rows??[]) as StudySessionRow[],context.unitId);','const history=studyHistoryForUnit(((rows??[]) as StudySessionRow[]).filter(s=>s.unit_id===context.unitId||s.lesson_id===startingPointId||s.lesson_id.startsWith("prereq-")).map(s=>({...s,unit_id:context.unitId})),context.unitId);')
s=s.replace('lines:["Four short questions, one at a time.","It is fine to choose ‘I\'m not sure yet’. This helps choose your first step."],example:"",support:""','secondsPerQuestion:5,lines:["10 short prerequisite questions, one at a time. Five seconds each; the next question opens automatically.","Choose the best answer before time runs out. Timeouts need another check, not an automatic judgement about your skills."],example:"",support:""')
s=s.replace('home.kind==="baseline"?content.baseline:', 'home.kind==="baseline"?startingPointQuestions:').replace('`${content.version}-baseline`','startingPointId')
p.write_text(s,encoding='utf-8')
p=Path('src/lib/mini-study.ts');s=p.read_text().replace('questions: StudyQuestion[];','questions: StudyQuestion[]; secondsPerQuestion?:number;');p.write_text(s,encoding='utf-8')
p=Path('src/components/mini-study-player.tsx');s=p.read_text().replace('Four basic questions. It is fine not to know the answers yet.','10 short questions, five seconds each. The check moves on automatically.');s=s.replace('export function MiniStudyPlayer({card,initialGrade,check=checkMiniStudy,finish=finishMiniStudy}:PlayerProps) {','export function MiniStudyPlayer(props:PlayerProps) {\n if(props.card.secondsPerQuestion&&!props.initialGrade)return <TimedStartingPoint {...props}/>;\n return <UntimedStudyPlayer {...props}/>;\n}\nexport function UntimedStudyPlayer({card,initialGrade,check=checkMiniStudy,finish=finishMiniStudy}:PlayerProps) {');s='import {TimedStartingPoint} from "./timed-starting-point";\n'+s;s=s.replace('import {TimedStartingPoint} from "./timed-starting-point";\n"use client";','"use client";\nimport {TimedStartingPoint} from "./timed-starting-point";');s=s.replace('type PlayerProps=', 'export type PlayerProps=');p.write_text(s,encoding='utf-8')
p=Path('src/components/mini-study-report.tsx');s=p.read_text();s='import {startingPointRoute} from "@/lib/starting-point";\n'+s;s=s.replace('<dl className="mt-5', '{row.summary.baseline?.feedback.some(f=>f.questionId.startsWith("prereq:"))&&<p className="mt-4 font-semibold">Starting route: {startingPointRoute(row.summary.baseline)}. Provisional guidance for teaching, not a grade.</p>}\n      <dl className="mt-5');p.write_text(s,encoding='utf-8')
p=Path('supabase/migrations/202609160002_ten_question_starting_point.sql');s=Path('supabase/migrations/202609080002_mini_study_optional_more.sql').read_text().split('create or replace function public.finish_mini_study')[0];s=s.replace("if kind_value='baseline' and baseline_exists then", "if kind_value='baseline' and ((lesson_value='it-prerequisites-10-v1' and exists(select 1 from public.mini_study_sessions where learner_id=learner_uuid and lesson_id=lesson_value and status='completed')) or (lesson_value<>'it-prerequisites-10-v1' and baseline_exists)) then");s=s.replace("if kind_value='daily' and not baseline_exists then", "if kind_value='daily' and not baseline_exists and not exists(select 1 from public.mini_study_sessions where learner_id=learner_uuid and lesson_id='it-prerequisites-10-v1' and status='completed') then");p.write_text(s,encoding='utf-8')
