"use client";

import Link from "next/link";
import { useEffect, useMemo, useState, useTransition } from "react";
import { saveAtomAttempt } from "@/app/actions/atom-learning";
import { levelDifficulty, markQuestion, nextDifficulty, orderByTargetDifficulty, questionsFor, scoreQuestion } from "@/lib/atom-question-bank";
import { topicKey, type LearningProgress } from "@/lib/learning-progress";
import type { PearsonTopic, PearsonUnit } from "@/lib/pearson-curriculum";

export function AdaptivePracticeSession({ unit, topic, storageKey }: { unit: PearsonUnit; topic: PearsonTopic; storageKey: string }) {
  const baseQuestions = useMemo(()=>questionsFor(unit,topic),[unit,topic]);
  const [questions,setQuestions]=useState(baseQuestions);
  const [startedAt]=useState(()=>Date.now()), [syncPending,startSync]=useTransition(), [syncMessage,setSyncMessage]=useState("");
  const [index,setIndex]=useState(0), [answer,setAnswer]=useState<string>("");
  const [checked,setChecked]=useState(false), [hint,setHint]=useState(false), [hintCount,setHintCount]=useState(0), [results,setResults]=useState<{questionId:string;correct:boolean;hintsUsed:number;awardedMarks:number;answer:string}[]>([]);
  const question=questions[index], correct=checked&&markQuestion(question,answer);
  useEffect(()=>{let active=true;queueMicrotask(()=>{if(!active)return;let saved:LearningProgress={topics:{}};try{saved=JSON.parse(localStorage.getItem(storageKey)??"")}catch{}const target=levelDifficulty(saved.level??saved.recommendedLevel??"Core");setQuestions(orderByTargetDifficulty(baseQuestions,target))});return()=>{active=false}},[baseQuestions,storageKey]);
  function check(){ if(!answer.trim())return; setChecked(true); }
  function next(){ const nextResults=[...results,{questionId:question.id,correct,hintsUsed:hint?1:0,awardedMarks:scoreQuestion(question,answer),answer}]; if(index===questions.length-1){save(nextResults);setResults(nextResults);}else{const target=nextDifficulty(question.difficulty,correct);setQuestions(current=>[...current.slice(0,index+1),...orderByTargetDifficulty(current.slice(index+1),target)]);setResults(nextResults);setIndex(index+1);setAnswer("");setChecked(false);setHint(false);} }
  if(results.length===questions.length){const maxMark=questions.reduce((sum,item)=>sum+item.marks,0),mark=results.reduce((sum,item)=>sum+item.awardedMarks,0),percent=Math.round(mark/maxMark*100);return <section className="card mx-auto max-w-3xl text-center"><p className="eyebrow">Session complete</p><h1 className="mt-3 text-5xl font-bold">{percent}%</h1><p className="mt-2 font-semibold">{mark} of {maxMark} indicative marks</p><p className="mt-3 text-slate-600">{percent>=75?"This topic is looking secure. Try the unit paper next.":"Review the quick lesson, then retry a fresh set to strengthen this topic."}</p>{(syncPending||syncMessage)&&<p role="status" className="mt-4 rounded-xl bg-slate-100 p-3 text-sm">{syncPending?"Adding this session to your report…":syncMessage}</p>}<div className="mt-7 flex flex-wrap justify-center gap-3"><Link className="button" href={`/curriculum/units/${unit.code}/papers`}>Try a unit paper</Link><Link className="button-secondary" href={`/curriculum/units/${unit.code}/topics/${encodeURIComponent(topic.code)}`}>Review lesson</Link></div></section>}
  return <div className="mx-auto max-w-3xl"><div className="mb-5 flex items-center gap-4"><span className="text-sm font-bold">{index+1} of {questions.length}</span><div className="h-2 flex-1 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-teal-600" style={{width:`${(index+1)/questions.length*100}%`}}/></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">Level {question.difficulty}</span></div><section className="card"><p className="eyebrow">{topic.code} · {question.commandWord} · {question.marks} {question.marks===1?"mark":"marks"}</p><h1 className="mt-4 text-2xl font-bold leading-9">{question.prompt}</h1>{question.options?<div className="mt-6 grid gap-3">{question.options.map((option,i)=><button disabled={checked} onClick={()=>setAnswer(String(i))} className={`rounded-xl border p-4 text-left ${answer===String(i)?"border-teal-600 bg-teal-50":"border-slate-200"}`} key={option}>{option}</button>)}</div>:<><textarea disabled={checked} value={answer} onChange={event=>setAnswer(event.target.value)} className="input mt-6 min-h-40" placeholder={`Write an applied answer of about ${question.minimumWords} words. Use the context, linked reasoning and evidence.`}/><p className="mt-2 text-xs text-slate-500">Indicative minimum {question.minimumWords} words · longer responses are checked against key content and reasoning before teacher review.</p></>}{!checked&&<div className="mt-5 flex flex-wrap gap-3"><button className="button" onClick={check}>Check answer</button><button className="button-secondary" onClick={()=>{if(!hint)setHintCount(value=>value+1);setHint(true)}}>Give me a hint</button></div>}{hint&&!checked&&<p className="mt-4 rounded-xl bg-amber-50 p-4 text-amber-950"><strong>Hint:</strong> {question.hint}</p>}{checked&&<div className={`mt-6 rounded-2xl p-5 ${correct?"bg-teal-50 text-teal-950":"bg-amber-50 text-amber-950"}`}><h2 className="text-xl font-bold">{question.options?(correct?"Correct. Well done":"Not quite. Learn from this one"):(correct?"Key points found and indicatively secure":"More development needed")}</h2><p className="mt-2 leading-7">{question.explanation}</p>{question.options&&!correct&&<p className="mt-3 font-semibold">Correct answer: {question.options[question.answer??0]}</p>}<details className="mt-4 rounded-xl bg-white/70 p-4 text-left"><summary className="cursor-pointer font-bold">Mark scheme and model response</summary><ul className="mt-3 grid gap-1 text-sm">{question.markScheme.map(point=><li key={point}>□ {point}</li>)}</ul><p className="mt-4 text-sm"><strong>Model response:</strong> {question.modelAnswer}</p>{!correct&&<p className="mt-3 text-sm"><strong>Common misconception:</strong> {question.misconception}</p>}</details><button className="button mt-5" onClick={next}>{index===questions.length-1?"See my results":"Next question →"}</button></div>}</section></div>;
  function save(items:{questionId:string;correct:boolean;hintsUsed:number;awardedMarks:number;answer:string}[]){const maxMark=questions.reduce((sum,item)=>sum+item.marks,0),mark=items.reduce((sum,item)=>sum+item.awardedMarks,0),percent=Math.round(mark/maxMark*100);let saved:LearningProgress={topics:{}};try{saved=JSON.parse(localStorage.getItem(storageKey)??"")}catch{}const key=topicKey(unit.code,topic.code), previous=saved.topics[key]??{};localStorage.setItem(storageKey,JSON.stringify({...saved,currentPosition:{unitCode:unit.code,topicCode:topic.code,section:"practice"},topics:{...saved.topics,[key]:{...previous,startedAt:previous.startedAt??new Date().toISOString(),lessonCompletedAt:previous.lessonCompletedAt??new Date().toISOString(),practiceScore:percent,hintsUsed:(previous.hintsUsed??0)+hintCount,currentSection:"practice"}}}));startSync(async()=>{const response=await saveAtomAttempt({kind:"topic_practice",unitCode:unit.code,topicCode:topic.code,paperMode:null,selectedLevel:saved.level??saved.recommendedLevel??"Core",percentage:percent,mark,maxMark,hintsUsed:hintCount,activeSeconds:Math.max(1,Math.round((Date.now()-startedAt)/1000)),results:items.map((item,itemIndex)=>({id:item.questionId,difficulty:questions[itemIndex].difficulty,correct:item.correct,hintsUsed:item.hintsUsed,marks:questions[itemIndex].marks,awardedMarks:item.awardedMarks,answer:item.answer}))});setSyncMessage(response.message)});}
}
