"use client";

import { useActionState } from "react";
import { updateAdminSettings, type ActionState } from "@/app/actions/learning";

export function AdminSettingsForm({settings}:{settings:{learner_evidence_years:number;audit_log_years:number;archived_class_years:number;deletion_requires_approval:boolean}|null}){
  const[state,action,pending]=useActionState<ActionState,FormData>(updateAdminSettings,{});
  return <form action={action} className="card grid gap-4"><div><p className="eyebrow">Data governance</p><h2 className="mt-2 text-2xl font-bold">System and retention settings</h2></div><label className="grid gap-1 text-sm font-semibold">Organisation display label<input className="input" name="organisationLabel" placeholder="SCCB Digital Learning Hub"/></label><div className="grid gap-3 sm:grid-cols-3"><label className="grid gap-1 text-sm font-semibold">Learner evidence years<input className="input" type="number" min="1" max="25" name="learnerEvidenceYears" defaultValue={settings?.learner_evidence_years??7}/></label><label className="grid gap-1 text-sm font-semibold">Audit log years<input className="input" type="number" min="1" max="25" name="auditLogYears" defaultValue={settings?.audit_log_years??7}/></label><label className="grid gap-1 text-sm font-semibold">Archived class years<input className="input" type="number" min="1" max="25" name="archivedClassYears" defaultValue={settings?.archived_class_years??7}/></label></div><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="deletionRequiresApproval" defaultChecked={settings?.deletion_requires_approval??true}/>Require explicit approval before learner-data deletion</label><button className="button justify-self-start" disabled={pending}>{pending?"Saving…":"Save administrator settings"}</button>{state.message&&<p className={`text-sm ${state.ok?"text-teal-800":"text-red-700"}`}>{state.message}</p>}</form>;
}
