"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {expertiseLevels,type ExpertiseLevel} from "@/lib/learning-catalog";
import {topicKey,type LearningProgress} from "@/lib/learning-progress";
import {teachingSequenceFor} from "@/lib/btec-teaching";
import type {PearsonTopic,PearsonUnit} from "@/lib/pearson-curriculum";
import {TopicWorksheet} from "@/components/topic-worksheet";

export function AtomTopicHub({unit,topic,storageKey,catchUp=false,evidenceStage="learning"}:{unit:PearsonUnit;topic:PearsonTopic;storageKey:string;catchUp?:boolean;evidenceStage?:"before"|"learning"|"progress_check_1"|"progress_check_2"|"after"}){
 const [level,setLevel]=useState<ExpertiseLevel>("Core"),[part,setPart]=useState(0),[answerShown,setAnswerShown]=useState(false),[score,setScore]=useState<number|null>(null);
 const cards=useMemo(()=>teachingSequenceFor(unit,topic,level),[unit,topic,level]),card=cards[part];
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(!active)return;const saved=readProgress(storageKey);setLevel(saved.level??saved.recommendedLevel??"Core");setScore(saved.topics[topicKey(unit.code,topic.code)]?.practiceScore??null)});return()=>{active=false}},[storageKey,topic.code,unit.code]);
 function choose(next:ExpertiseLevel){setLevel(next);setPart(0);setAnswerShown(false);const saved=readProgress(storageKey);localStorage.setItem(storageKey,JSON.stringify({...saved,level:next}))}
 function move(next:number){setPart(Math.max(0,Math.min(cards.length-1,next)));setAnswerShown(false)}
 const practiceHref=`/curriculum/units/${unit.code}/topics/${encodeURIComponent(topic.code)}/practice`;
 const supportedUnitCode=worksheetUnitCode(unit.code);
 return <div className="grid gap-6">
  <section className="card border-teal-200 bg-gradient-to-br from-teal-950 to-teal-700 text-slate-950"><div className="flex flex-wrap items-start justify-between gap-5"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-widest text-teal-800">Learn · Practice · Master</p><h2 className="mt-3 text-3xl font-bold">Learn every concept, then prove it</h2><p className="mt-3 text-slate-700">Short explanations, vocational examples and pause-and-check questions lead into adaptive practice and papers.</p></div><div className="rounded-2xl bg-teal-50 p-4"><p className="text-xs uppercase tracking-wide text-teal-900">Current evidence</p><p className="mt-1 text-2xl font-bold">{score==null?"New topic":`${score}%`}</p></div></div></section>
  <section className="card"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Choose your route</p><h2 className="mt-2 text-2xl font-bold">How much support would you like?</h2></div><div className="flex flex-wrap items-center gap-3"><p className="text-sm text-slate-600">The question difficulty also follows this choice.</p>{supportedUnitCode&&!catchUp&&<Link className="button-secondary button-small" href={`/curriculum/units/${unit.code}/topics/${encodeURIComponent(topic.code)}?catchup=1#worksheet`}>Missed this lesson? Start catch-up</Link>}</div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{expertiseLevels.map(item=><button className={`rounded-xl border p-4 text-left ${level===item?"border-teal-600 bg-teal-50":"border-slate-200"}`} key={item} onClick={()=>choose(item)}><strong>{item}</strong><span className="mt-1 block text-xs text-slate-600">{item==="Support"?"Plain-language teaching and gentler questions":item==="Core"?"Balanced teaching and applied practice":item==="Stretch"?"Less scaffolding and faster access to questions":"Advanced questions and project route"}</span></button>)}</div>{(level==="Stretch"||level==="Challenge")&&<div className="mt-4 flex flex-wrap items-center gap-3 rounded-xl bg-violet-50 p-4"><strong>{level} route:</strong><span className="text-sm text-slate-700">You may review the cards or move directly to independent evidence.</span><Link className="button-secondary button-small" href={practiceHref}>Skip to adaptive questions</Link>{level==="Challenge"&&<Link className="button-secondary button-small" href={`/curriculum/units/${unit.code}/project`}>Open Challenge project</Link>}</div>}</section>
  <section className="grid gap-5 lg:grid-cols-[1fr_18rem]"><article className="card"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Quick lesson · {part+1} of {cards.length}</p><h2 className="mt-2 text-2xl font-bold">{card.title}</h2><p className="mt-2 text-sm text-slate-600">{card.purpose}</p></div><span className="rounded-full bg-teal-100 px-3 py-2 text-sm font-bold text-teal-900">2 to 4 min</span></div>
    <div className="mt-6 grid gap-4">{card.points.map(point=><section className="rounded-2xl bg-slate-50 p-5" key={point.concept}><h3 className="text-lg font-bold">{point.concept}</h3><p className="mt-3 leading-7 text-slate-700">{point.explanation}</p><div className="mt-4 rounded-xl border-l-4 border-blue-500 bg-white p-4"><p className="text-xs font-bold uppercase tracking-wide text-blue-800">Vocational example</p><p className="mt-2 text-sm leading-6">{point.example}</p></div></section>)}</div>
    {card.workedSteps&&<div className="mt-5 rounded-xl bg-blue-50 p-5"><p className="font-bold">Worked step by step</p><ol className="mt-3 grid gap-2 text-sm">{card.workedSteps.map((step,index)=><li key={step}><strong>{index+1}.</strong> {step}</li>)}</ol></div>}
    <div className="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-950"><strong>Common mistake:</strong> {card.misconception}</div>
    <div className="mt-5 rounded-xl border border-violet-200 p-5"><p className="text-xs font-bold uppercase tracking-wide text-violet-800">Pause and check</p><p className="mt-2 font-semibold">{card.checkQuestion}</p>{answerShown?<p className="mt-3 rounded-xl bg-violet-50 p-4 text-sm"><strong>Check answer:</strong> {card.checkAnswer}</p>:<button className="button-secondary button-small mt-4" onClick={()=>setAnswerShown(true)}>Reveal check answer</button>}</div>
    <div className="mt-6 flex flex-wrap gap-3"><button className="button-secondary" disabled={part===0} onClick={()=>move(part-1)}>Previous</button>{part<cards.length-1?<button className="button" onClick={()=>move(part+1)}>Continue lesson →</button>:<Link className="button" href={practiceHref}>Start adaptive questions →</Link>}</div>
   </article><aside className="grid content-start gap-4"><div className="card"><p className="eyebrow">Lesson map</p><ol className="mt-3 grid gap-2 text-sm">{cards.map((item,index)=><li key={item.id}><button className={`w-full rounded-lg p-2 text-left ${index===part?"bg-teal-50 font-bold text-teal-900":"hover:bg-slate-50"}`} onClick={()=>move(index)}>{index+1}. {item.title}</button></li>)}</ol></div><Link className="card hover:border-teal-400" href={practiceHref}><p className="eyebrow">Practice</p><h3 className="mt-2 text-xl font-bold">Adaptive questions</h3><p className="mt-2 text-sm text-slate-600">Hints, mark schemes and model answers.</p></Link><Link className="card hover:border-violet-400" href={`/curriculum/units/${unit.code}/papers`}><p className="eyebrow">Test</p><h3 className="mt-2 text-xl font-bold">Unit papers</h3><p className="mt-2 text-sm text-slate-600">Knowledge, applied and assignment rehearsal.</p></Link><Link className="card hover:border-blue-400" href="/progress"><p className="eyebrow">Track</p><h3 className="mt-2 text-xl font-bold">My progress</h3><p className="mt-2 text-sm text-slate-600">Strengths, needs and next steps.</p></Link></aside></section>
  {supportedUnitCode&&<TopicWorksheet unitCode={supportedUnitCode} topicCode={topic.code} topicTitle={topic.title} catchUp={catchUp} evidenceStage={evidenceStage}/>}
  </div>
 }
function readProgress(storageKey:string):LearningProgress{try{return JSON.parse(localStorage.getItem(storageKey)??"") as LearningProgress}catch{return{topics:{}}}}
function worksheetUnitCode(value:string):"2"|"4"|"6"|null{return value==="2"||value==="4"||value==="6"?value:null}
